### ISSUE TITLE
successful Joining on live demo but no video

### ISSUE THREAD

**Issue by tayoraph** [AgoraIO/Tools#105]
Hi , please help . 

i created successfully to host and join a channel , i couldn't get the video to display on the audience side. 

i m testing with chrome browser as host and ingconito as audience . 

please any help will be appreciated

**Comment by plutoless** [comment]
are you on web platform? do you have an example project or source code which i can refer to?

**Comment by plutoless** [comment]
you may also try out this https://webdemo.agora.io/agora-web-showcase/

**Comment by fullstack10** [comment]
I have tried the above link i am also facing the same issue can you please help me 
![image](https://user-images.githubusercontent.com/69449472/109508749-2f438700-7ac6-11eb-8426-bf2cc1787335.png)
