### ISSUE TITLE
Create dynamic token creation by php code

### ISSUE THREAD

**Issue by algosoftech** [AgoraIO/Tools#109]
Hello,
I have use below code but it's not working. I got error "client join failed NO_AUTHORIZED".

include("../src/RtcTokenBuilder.php");

$appID = "d6e3xxxxxxxxxxxxxxxxxxxx990f4e8b";
$appCertificate = "6dbcxxxxxxxxxxxxxxxxxxxx7cf3c92a";
echo $channelName = "7d7236545jh234u6h54n34393460bdda";
$uid = 9854785632;
$uidStr = "9854785632";
echo '<br>'.$role = RtcTokenBuilder::RolePublisher;
$expireTimeInSeconds = 3600;
echo '<br>'.$currentTimestamp = (new DateTime("now", new DateTimeZone('UTC')))->getTimestamp();
echo '<br>'.$privilegeExpiredTs = $currentTimestamp + $expireTimeInSeconds;

$token = RtcTokenBuilder::buildTokenWithUid($appID, $appCertificate, $channelName, $uid, $role, $privilegeExpiredTs);
echo '<br>Token with int uid: ' . $token . PHP_EOL;

$token = RtcTokenBuilder::buildTokenWithUserAccount($appID, $appCertificate, $channelName, $uidStr, $role, $privilegeExpiredTs);
echo '<br><br>Token with user account: ' . $token . PHP_EOL;

 Please help us with the resolution of this critical point

**Comment by plutoless** [comment]
hi, could you pls provide a token you just generated? i can help check what might go wrong.
