### ISSUE TITLE
Please add Swift support

### ISSUE THREAD

**Issue by brightfuture** [AgoraIO/Tools#110]
AWS Lambda now supports Swift
now I hope I can implement this with Swift some day :)

**Comment by yoreland** [comment]
Do you mean token generator for swift?
Would you mind to raise a PR for swift version? :)

**Comment by brightfuture** [comment]
@yoreland i hope i can use token generator with Swift
but i don't know how to achieve that

**Comment by plutoless** [comment]
@brightfuture we will take a look at this request :)

**Comment by shinriyo** [comment]
Is client-side generation without server not supported?
