### ISSUE TITLE
Token expiration

### ISSUE THREAD

**Issue by mmo-uy** [AgoraIO/Tools#117]
Hi i'm using node js version of the repository to generate token. I have some questions about token generation and expiration time:

- Expiration time is always 3600? => My implementation needs to "save token call for later" so with this scenario I was generating my token like this:
`Date of call in Timestamp + current time in Timestamp` and this is not working. Then i tried to assign 1 year durationin timestamp (I know it's exagerated, it was only testing purposes)
So my question is: if I should generate my token with 3600 as duration and not save this token in DB and instead use it once per "connection"=> (video call with one hour duration) because it's useless after.
Correct me if I'm wrong or give me some advice.
Thanks in advance

**Comment by plutoless** [comment]
@desarrollomaxijoga10 you should use a new token every time you join a channel. the token expiration time can be any value between 0~24hours. if you set the duration as 3600, the token became useless after it's expired yes.

**Comment by mmo-uy** [comment]
@plutoless thanks for your answer, indeed I realize what you mention and now I adapted everything to be exactly as should be. I close this now.
