### ISSUE TITLE
Where is the token generate sample of C# ?

### ISSUE THREAD

**Issue by gavinfang-fi** [AgoraIO/Tools#125]
The link (https://github.com/AgoraIO/Tools/blob/master/DynamicKey/AgoraDynamicKey/csharp/src/AgoraIO/Media/AccessToken.cs) in the doc: is broken.

**Comment by plutoless** [comment]
sorry it's moved here
https://github.com/AgoraIO/Tools/tree/deprecated/DynamicKey/AgoraDynamicKey/csharp
i've updated the link in readme
