### ISSUE TITLE
Receiving 110 error when using `buildTokenWithAccount`

### ISSUE THREAD

**Issue by paarikan** [AgoraIO/Tools#130]
Hello,

I'm creating a token on a Node server and then attempting to join from a React Native client with the following lines:

Server:
`RtcTokenBuilder.buildTokenWithAccount(AGORA_CONFIG.appId, AGORA_CONFIG.appCertificate, channelName, 'user-id-1', AGORA_CONFIG.role, AGORA_CONFIG.privilegeExpiredTs),
`
Client:
`await audioEngine.current.joinChannelWithUserAccount(m.callToken, m.groupId, 'user-id-1')`

I receive a `110` error callback with the above when I expect to join successfully. I am successfully able to join when using uids like below:

Server:
`RtcTokenBuilder.buildTokenWithUid(AGORA_CONFIG.appId, AGORA_CONFIG.appCertificate, channelName, 0, AGORA_CONFIG.role, AGORA_CONFIG.privilegeExpiredTs),`
Client:
` await audioEngine.current.joinChannelWithAccount(m.callToken, m.groupId, null, 0)`

**Comment by plutoless** [comment]
could you pls share a token you generated with me?
