### ISSUE TITLE
I am using csharp code to generate the access token but this token is not working when i try to join a call 

### ISSUE THREAD

**Issue by fullstack10** [AgoraIO/Tools#131]
![image](https://user-images.githubusercontent.com/69449472/109475332-96981180-7a9b-11eb-8397-0dcabca822a0.png)

**Comment by Hoang-Minh** [comment]
I also run into the same issue. Any help ? I'm using the code below to generate my token:

```
AccessToken token = new AccessToken(_appId, _appCertificate, _channelName, _uid, _ts, _salt);
token.message.ts = _ts;
token.message.salt = _salt;
token.addPrivilege(Privileges.kJoinChannel, _expiredTs);

string result = token.build();
```


![image](https://user-images.githubusercontent.com/8659719/141204961-b4e2eb80-0bcf-41e5-bf0f-8010cd629d09.png)

**Comment by Hoang-Minh** [comment]
The c# code is broken. I was able to generate the token by using node js. Please fix the package to generate code in c#. Thank you !!!

**Comment by fullstack10** [comment]
i just prefix variable values in accesstoken.cs class which is mentioned below ,

        private uint _ts = 1111111;
        private uint _salt = 1;
        private uint _expiredTs = 1446455471;
        
        and while calling    AccessToken token = new AccessToken(appId, appCertificate, channelName, uid, ts, salt);
i am passing  uid = "0";
and its working 

 string uid = "0";  means you can use the same token for connecting a video call
 specific uid means you need two / more different access token to connect video call

**Comment by Hoang-Minh** [comment]
Thanks @fullstack10 . Its not working for me even if I passed uid = "0".
This is my generated token when passing uid = "0". However, when I used it for the demo (`https://github.com/AgoraIO-Community/AgoraWebSDK-NG`) it is not working.
`0063fb869e0755144ae9cd4a714201cf921IAA2bQNquudi3rrKnZFQfe6VdO/mPvqiZPHswcCB1DZuJlsFw2wh39v0EAABAAAAR/QQAAEAAQCvKDdW`

What does your token look like @fullstack10 ? Thank you

**Comment by fullstack10** [comment]
hi @Hoang-Minh ,
i am using https://github.com/AgoraIO/Tools/tree/master/DynamicKey/AgoraDynamicKey/csharp this code , and 
my token is 006970CA35de60c44645bbae8a215061b33IADNg9bfcUDIC1Qs1EedxluwYPEhU8Z66b8WHMWwqz0L9wx+f9gh39v0EAABAAAAR/QQAAEAAQCvKDdW
![image](https://user-images.githubusercontent.com/69449472/141421193-a0a98f45-1126-4747-acc7-837ff29f0f31.png)

**Comment by Hoang-Minh** [comment]
@fullstack10 Have you tried to use your key with the demo ?
https://webdemo.agora.io/agora-web-showcase/examples/Agora-Web-Tutorial-1to1-Web/

For me, key cannot be used to join if using csharp.
However, if I use the key generated from nodejs then it's working for me.

**Comment by fullstack10** [comment]
Yes I tried and now i am using this in my live project and its working

**Comment by Hoang-Minh** [comment]
@fullstack10 hmmm, that is so weird. It does not work for me at all. Its giving me this error in c#
![image](https://user-images.githubusercontent.com/8659719/141833486-745a4d1e-8ef3-4871-86e7-be049b9ac06d.png)

@yoreland Can you help me out please ? Thank you

**Comment by fullstack10** [comment]
Hi can you please provide me your appid and app secret so i will create a
token for you and tested with my code if anything different then i will
update you .

**Comment by Hoang-Minh** [comment]
@fullstack10 what is your email ? Thank you

**Comment by fullstack10** [comment]
Email : ***@***.***

**Comment by Hoang-Minh** [comment]
I think Github censors your email. Anyway, here is my agora info:
```
AppId: 3fb869e0755144ae9cd4a714201cf921
AppCertificate: edb6e4236aec4bf7a181898255dec8da
```

Thank you

**Comment by fullstack10** [comment]
hi , just replace below method in accesstoken.cs class. then it starts
working.

accesstoken.cs

  public void addPrivilege(Privileges kJoinChannel, uint expiredTs)
        {
           //  this.message.messages.Add((ushort)kJoinChannel, expiredTs);
        }

[image: image.png]

**Comment by Hoang-Minh** [comment]
Hmmm, commenting that part of code out will take out the privilege and expire time for  your token. It will have impact on the generated token. I thought you said that the code is working for you without commenting that out ? Am I correct ? Thank you

**Comment by fullstack10** [comment]
I tried with expiration time as well but its not working and then i did
this but the token which we generated from this code with comment this line
it will expire in 24 hours so its work for me.

**Comment by Hoang-Minh** [comment]
Got it. Thank you @fullstack10

**Comment by Hoang-Minh** [comment]
@fullstack10 FYI, my token is still not working even though I have commented the code that you said.
@yoreland : Are not not supporting/maintaining this package anymore ? I've been asking for help for more than a week and I have not got any response yet.

**Comment by fullstack10** [comment]
I will send you a code just use that and try again.

**Comment by Hoang-Minh** [comment]
Thank you @fullstack10

**Comment by Hoang-Minh** [comment]
@fullstack10 I figured out how to generate a token with expiration time. The problem lies in the _ts and _salt value. We need not to pass them in to the access token constructor. Below is my snippet code:

          ` var expireTime = 3600;
            var test = new DateTimeOffset(DateTime.UtcNow).ToUnixTimeSeconds();
            _expiredTs = (uint)(test + expireTime);

            string expected = "006970CA35de60c44645bbae8a215061b33IACV0fZUBw+72cVoL9eyGGh3Q6Poi8bgjwVLnyKSJyOXR7dIfRBXoFHlEAABAAAAR/QQAAEAAQCvKDdW";
            
            AccessToken token = new AccessToken(_appId, _appCertificate, _channelName, _uid);

            token.addPrivilege(Privileges.kJoinChannel, _expiredTs);
            string result = token.build();
            Assert.Equal(expected, result);`

**Comment by fullstack10** [comment]
Great , thank you so much now do you need the c# code.

**Comment by Hoang-Minh** [comment]
It would be nice too, if you can. Thank you very much

**Comment by fullstack10** [comment]
https://drive.google.com/file/d/1gZxSQHHWqpvc6hFkod0FUNExiHes_XKq/view?usp=sharing

**Comment by Hoang-Minh** [comment]
Thanks @fullstack10

**Comment by smnbh12345** [comment]
Hi  @ken39arg, 

I getting problem of expiring time. 

My code for generating the token in the dotnet, below is my code.  

```
public AgoraResponseDto testGenerateDynamicKey(AgoraRequestDto agoraRequestDto)
        {
            AgoraResponseDto agoraResponseTest = new AgoraResponseDto();

            var expireTime = 3600;
            var test = new DateTimeOffset(DateTime.UtcNow).ToUnixTimeSeconds();
             _expiredTs = (uint)(test + expireTime);


            //string expected = "006970CA35de60c44645bbae8a215061b33IACV0fZUBw+72cVoL9eyGGh3Q6Poi8bgjwVLnyKSJyOXR7dIfRBXoFHlEAABAAAAR/QQAAEAAQCvKDdW";
            AccessToken token = new AccessToken(_appId, _appCertificate, _channelName, _uid, _ts, _salt);
            token.message.ts = _ts;
            token.message.salt = _salt;
            token.addPrivilege(Privileges.kJoinChannel, _expiredTs);

            string result = token.build();
            agoraResponseTest.AppCertificate = _appCertificate;
            agoraResponseTest.AppId = _appId;
            agoraResponseTest.Channel = _channelName;
            agoraResponseTest.Token = result;
            return agoraResponseTest;
        }
```


and the response is : 

```
{
  "channel": "123456789",
  "appId": "43608641637444738faddaf9f89c62ed",
  "appCertificate": "822e318d19354931900df847f6198bdc",
  "token": "00643608641637444738faddaf9f89c62edIAChf81uxKKNViKXLlpTxPZaprXAH2gn54jJI32c/wILdCY59MtXoFHlEAABAAAAR/QQAAEAAQA/hmpi"
}

![TokenAuthenticationAndTime](https://user-images.githubusercontent.com/104567114/165741622-e426f8b5-e5b4-4117-9315-45c1de960db0.png)
![TokenAuthenticationAndTime](https://user-images.githubusercontent.com/104567114/165741698-4a1c5103-767a-4ef6-9c5a-faa445b3b0cc.png)

```
![TokenAuthenticationAndTime](https://user-images.githubusercontent.com/104567114/165741834-fb869d46-384c-432e-8710-e2f6eccd5c9c.png)

**Comment by sunshinexcode** [comment]
Change _appId and _appCertificate to the account information you applied for, run the UT of this file https://github.com/AgoraIO/Tools/blob/master/DynamicKey/AgoraDynamicKey/csharp/test/AgoraIO.Tests/RtcTokenBuilderTest.cs. Test the generated token on this website https://webdemo.agora.io/agora-web-showcase/examples/Agora-Web-Tutorial-1to1-Web/
