### ISSUE TITLE
CAN_NOT_GET_GATEWAY_SERVER

### ISSUE THREAD

**Issue by ToriomLab** [AgoraIO/Tools#133]
I generate token with php 
But When I use it in the video call get this error
https://share.getcloudapp.com/GGu6B7eX

Code tedails 
https://share.getcloudapp.com/6quQobA4

Token generated
Token with int uid:
006bd8bb407beab44c3b5c09579820716a2IACaoDsMG7kqVN3gczWqBcs5Y0PPg0RB9CfXk6p3VhmA/gx+f9hiBTIMIgCOQ5IFHvtBYAQAAQCut0BgAwCut0BgAgCut0BgBACut0Bg
Token with user account:
006bd8bb407beab44c3b5c09579820716a2IACLD/sILkveQhcGYxeK04BIifb1l+1D735ujSYAgA1w/gx+f9hiBTIMIgDIrKEEHvtBYAQAAQCut0BgAwCut0BgAgCut0BgBACut0Bg

**Comment by plutoless** [comment]
@ToriomLab as far as i can see the token itself if legal. could you pls share how you call joinChannel api in your client?

**Comment by ToriomLab** [comment]
Thanks to you 

I used this demo code
https://share.getcloudapp.com/NQuJmkPP

**Comment by plutoless** [comment]
it seems the code is not specifying uid from UI.

```
var options = {
  appid: null,
  channel: null,
  uid: null,
  token: null
};
```

try filling in the uid and use the one you used to calculate the token.

**Comment by ToriomLab** [comment]
I get same Error

**Comment by plutoless** [comment]
@ToriomLab what did you do? could you show me a complete file which has everything filled?

**Comment by ToriomLab** [comment]
Thanks A lot 

I path uid [here](https://prnt.sc/10nyoqg)  and it is work now
