### ISSUE TITLE
Python 3 Generated Token invalid  when trying to login to RTM in flutter app

### ISSUE THREAD

**Issue by demagomes** [AgoraIO/Tools#135]
Hey guys,

I generated the RTM token on Python 3 and it generates the below:

`Rtm Token: 006c2b49a24589e49b484150e765ae1e694IADuBOdsM+tXvWJe9ESKJpFu0w/5hZ/HbfLw60A7uhVeiWW5wpAAAAAAEADKkbMFnYFOYAEA6AMtPk1g`

But then trying to login on my Flutter App I get the below:

`Login error code 5.`

I double checked the userid are the same when creating the token and when loging in.

**Comment by plutoless** [comment]
@demagomes what is your rtm account?

**Comment by demagomes** [comment]
Hi there, thanks for fast response! Im not sure if the info below is what you need but here we go:

appID = "c2b49a24589e49b484150e765ae1e694"


Thanks

**Comment by plutoless** [comment]
@demagomes i'm talking about the rtm string account you used for login. there must be an account you used to call login function

**Comment by demagomes** [comment]
Hey @plutoless thanks for this. I used a string. So the function is as below:

Future<dynamic> login(String token, String userId)

So I used the token generated with the python 3 code and the userId i used a string as below:

await _client.login('006c2b49a24589e49b484150e765ae1e694IADuBOdsM+tXvWJe9ESKJpFu0w/5hZ/HbfLw60A7uhVeiWW5wpAAAAAAEADKkbMFnYFOYAEA6AMtPk1g', 'ademar');

I am guessing this is wrong so where do I get my string account from?

**Comment by plutoless** [comment]
umm this is correct. are you sure you have used the correct certificate?
does it look like this? 
2aae325b0c65*********

**Comment by demagomes** [comment]
that is correct, ending in 2f6.

**Comment by demagomes** [comment]
would you advise trying another generator, lets say python 2 for example?

**Comment by plutoless** [comment]
@demagomes does it work with this?
https://webdemo.agora.io/agora-web-showcase/examples/Agora-RTM-Tutorial-Web/

**Comment by demagomes** [comment]
It does after I generated a new token! 
But still returns me error code 5 when I try to login through Flutter. 

One observation, im connecting to RTC and RTM on the same screen. Not sure if it is relevant or not.

**Comment by demagomes** [comment]
hey @plutoless separating the RTC and RTM code in different widgets worked so I assume it is something with the implementation of both together. As an issue you suppose we can close this one; cheers
