### ISSUE TITLE
php create access token without uid

### ISSUE THREAD

**Issue by ziasultan2** [AgoraIO/Tools#141]
How can I create access token without uid. I want to give it multiple user to access channel. Currently I'm building with this but here I've to give int uid but I want to build without uid
RtcTokenBuilder::buildTokenWithUid(
            env('AGORA_APP_ID'),
            env('AGORA_APP_CERTIFICATE'),
            $channelName,
            $uid,
            RtcTokenBuilder::RoleAttendee,
            $privilegeExpiredTs
        );

**Comment by plutoless** [comment]
just provide 0 for uid.

**Comment by ziasultan2** [comment]
so If I put 0 shouldn't I pass uid when join channel?

**Comment by plutoless** [comment]
when you calculate a token with uid 0. that means do not check uid - so any user can join this channel with this token.
