### ISSUE TITLE
Call to a member function addPrivilege() on null PHP Laravel 8

### ISSUE THREAD

**Issue by maheshbhattaraai** [AgoraIO/Tools#148]
appID check failed, should be a non-empty string

    "message": "Call to a member function addPrivilege() on null",
    "exception": "Error",

**Comment by yoreland** [comment]
Can you help to provide more information? For example, which token builder you get this error? Is it rtmTokenBuilder?

**Comment by maheshbhattaraai** [comment]
Thanks for reply sir, i resolved the issue.
