### ISSUE TITLE
How to test RtcTokenBuilder?

### ISSUE THREAD

**Issue by nilsreichardt** [AgoraIO/Tools#158]
Is there a way to write tests for `RtcTokenBuilder`? I want to validate if the parameters are correct, like you can do it with JWTs:

```ts
import { verify } from "jsonwebtoken";

it("generates token with valid payload", () => {
        const currentTimestamp = getCurrentTimestampInSec();
        const token = new JitsiJwtGenerator(app_secret, app_id, hostname).generateJwt({
            meetingId: meetingId,
            isJitsiModerator: isModerator,
            expiresInMinutes: 1,
            userName: userName,
            userId: userId,
            groupId: groupId
        });

        const parsedToken = parseToken(token);

        expect(parsedToken.room).equals(meetingId)
        // expect(parsedToken.moderator).equals(isModerator) <-- We test this below
        expect(parsedToken.exp).equals(currentTimestamp + 60)
        expect(parsedToken.context.group).equals(groupId)
        expect(parsedToken.context.user.id).equals(userId)
        expect(parsedToken.context.user.name).equals(userName)
    });
```

**Comment by plutoless** [comment]
unlike jwt token. you cannot parse a token back to readable information. is there any reason you want to do that?

**Comment by nilsreichardt** [comment]
Yes, I want to write a test similar I showed in the description. I want to call a method with my parameters and this method returns a token. After that I want to check if in this token are my passed parameters, like `uid`, `role`, `channelName`, etc.

**Comment by plutoless** [comment]
@nilsreichardt unfortunately you can't do that. we compare your token by generating a token using same algorithm and parameters and compare them. we don't convert it back to raw info either. As long as you are using our original algorithm and correct parameter, the token generated should be correct.

**Comment by 0xdevalias** [comment]
@nilsreichardt I haven't verified this when running, but looking at the source..

We can see the source for `buildTokenWithAccount` here:

- https://github.com/AgoraIO/Tools/blob/a27ccdd7bf29463f2755c8fa16e82efc1a366f59/DynamicKey/AgoraDynamicKey/nodejs/src/RtcTokenBuilder.js#L60-L71

It uses `AccessToken`, which is defined at:

- https://github.com/AgoraIO/Tools/blob/a27ccdd7bf29463f2755c8fa16e82efc1a366f59/DynamicKey/AgoraDynamicKey/nodejs/src/AccessToken.js

You can see the `build` function within this, that returns `version + token.appID + content.toString('base64')`:

- https://github.com/AgoraIO/Tools/blob/a27ccdd7bf29463f2755c8fa16e82efc1a366f59/DynamicKey/AgoraDynamicKey/nodejs/src/AccessToken.js#L23-L46

There is also the `fromString` function defined in that same file:

- https://github.com/AgoraIO/Tools/blob/a27ccdd7bf29463f2755c8fa16e82efc1a366f59/DynamicKey/AgoraDynamicKey/nodejs/src/AccessToken.js#L52-L79

Based on that, it looks like you should be able to recover some, if not most/all of the parameters you want, and thus be able to write some tests for them.

Let me know how you go with this, would be interested to hear!

**Comment by toklive** [comment]
@plutoless is there documentation or can you clarify the details on the tokenbuilder. I am specifically looking for the difference between the below two methods. C# example..

What is this property does this._salt = salt;?

```
 public AccessToken(string appId, string appCertificate, string channelName, string uid)
        {
            _appId = appId;
            _appCertificate = appCertificate;
            _channelName = channelName;
            _uid = uid;
        }

        public AccessToken(string appId, string appCertificate, string channelName, string uid, uint ts, uint salt)
        {
            this._appId = appId;
            this._appCertificate = appCertificate;
            this._channelName = channelName;
            this._uid = uid;
            this._ts = ts;
            this._salt = salt;
        }
```
