### ISSUE TITLE
RTC Token invalid c# dotnet core 5.0

### ISSUE THREAD

**Issue by sherazakbar50** [AgoraIO/Tools#162]
I generated Token using c# for RTC and RTM. For RTM, its working perfectly fine but for RTC i am getting the error. The token is
"006cd972ece20434a42a3c1ddeea9e479e1IAAE6aAi7OSWBttPaNC/MgBCEcXK5gGrAb1+Ns6LCLNW034WEjqlc6GMEAAKJ52HogrXYAEAAgASx9Vg"

![image](https://user-images.githubusercontent.com/5244985/123416470-1cd5e780-d5a6-11eb-9f6f-b3ad67d3a9b3.png)

**Comment by yoreland** [comment]
can you check which channel name and UID you are using to join in the channel?

**Comment by sherazakbar50** [comment]
Thanks. I was using channel name in lower case in token while in upper case in SDK. Its a suggestion if case insensitive rooms are created if possible. Thanks for the help.
