### ISSUE TITLE
Firefox cannot establish a connection to server  at wss

### ISSUE THREAD

**Issue by sherazakbar50** [AgoraIO/Tools#163]
I am using Agora.io RTC SDK 4.5 and its working perfectly fine in all browsers but creating an issue in Mozilla Firefox only. Its disconnecting from socket as the error image is attached below.  

![image](https://user-images.githubusercontent.com/5244985/123795151-21c7cd80-d8fd-11eb-8ecd-ec61a35500aa.png)

**Comment by yoreland** [comment]
can you have a quick check on 
https://webdemo.agora.io/agora-web-showcase/examples/Agora-RTM-Tutorial-Web/
seems it works on my side with Firefox 89.0.2
