### ISSUE TITLE
[Node] Can't able to Generate Token in Server

### ISSUE THREAD

**Issue by coder-Aayush** [AgoraIO/Tools#172]
Hi, I have a flutter app with agora setup and I am generating agora RTC token from the cloud function. Every time I generate a token it says 
```
err RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received 1_626_013_391_434 
```
Code
```ts
async function createAgoratoken(date: any) {
// DateTime.now().millisecondsSinceEpoch
    return await RtcTokenBuilder.buildTokenWithUid(functions.config().agora.appid, functions.config().agora.certificate, "some", 0 , RtcRole.PUBLISHER, date);
// date is from flutter side
}
```
I think the error is from Date.

**Comment by yoreland** [comment]
seems the format of date is problematic, one possible solution is you could convert date to long and transfer it.

**Comment by coder-Aayush** [comment]
> seems the format of date is problematic, one possible solution is you could convert date to long and transfer it.

Ya solve the issue. Thanks

**Comment by coder-Aayush** [comment]
> seems the format of date is problematic, one possible solution is you could convert date to long and transfer it.

Ya solve the issue. Thanks
