### ISSUE TITLE
[Java] why can't i use uid when generating token?

### ISSUE THREAD

**Issue by tientai241102** [AgoraIO/Tools#178]
I have generated token token with uid of 0 but when uid is non-zero, my token is unusable.
<img width="927" alt="Screen Shot 2021-07-25 at 20 54 12" src="https://user-images.githubusercontent.com/72411896/126901673-ad93ed60-5223-47d8-b64b-f65d9ef1960f.png">

**Comment by yoreland** [comment]
Sorry for late response, The sample seems no issue.
Can you test your token on this demo
https://webdemo.agora.io/basicVideoCall/index.html

**Comment by tientai241102** [comment]
It's okay, I used it. Thank you very much.
