### ISSUE TITLE
使用SimpleTokenBuilder生成的token不能用

### ISSUE THREAD

**Issue by aberson-xie** [AgoraIO/Tools#18]
根据官方的token generator文档，文档中参考了github上的路径为（agoraIO/toolsDynamicKey/AgoraDynamicKey/java）的代码，生成的token不可用。
操作步骤：
1.运行sample（sample/io/agora/media/sample/）下的BuilderTokenSimple生成token。
2.运行路径为（Basic-Audio-Call/One-to-One-Voice/Agora-Android-Voice-Tutorial-1to1）的安卓项目，（appId和token都已经设置好了），看不到视频界面。
3.使用官网提供的临时token，一切正常。

不知道原因在哪，希望大神们给点意见

**Comment by plutoless** [comment]
token生成的channel name和uid与加入频道时的频道名和uid一致吗

**Comment by aberson-xie** [comment]
频道名是一致的，uid不清楚。调用方使用的是安卓，安卓有个joinChannel方法，方法中有一个参数，是int类型，不知道是不是这个，文档上说这个参数可不传，就默认给了0
| |
mhd
|
|
邮箱：aberxie@163.com
|

Signature is customized by Netease Mail Master

在2019年07月20日 20:27，Qianze Zhang 写道：

token生成的channel name和uid与加入频道时的频道名和uid一致吗

**Comment by plutoless** [comment]
给0的话会随机分配uid，如果用token最好指定一下uid，然后算token的时候确保用一样的频道名和uid

**Comment by JonathanStrangeHelium** [comment]
这个和login的token一样吗？
login的时候可能还没有频道，我看其它语言生成token都没有频道参数。有点儿懵

**Comment by aberson-xie** [comment]
这个没有登录，初始化视频组件后，直接根据appId，频道名，和token加入频道的。
| |
aberson
|
|
aberxie@163.com
|
签名由网易邮箱大师定制


在2019年07月22日 07:36，Hejian<notifications@github.com> 写道：

这个和login的token一样吗？
login的时候可能还没有频道，我看其它语言生成token都没有频道参数。有点儿懵

**Comment by aberson-xie** [comment]
@plutoless uid指定了，还是看不到视频界面。用的andriod下的这个方法。
![image](https://user-images.githubusercontent.com/47856925/61600989-09a59900-ac66-11e9-840b-45afee5b8b62.png)

**Comment by aberson-xie** [comment]
@plutoless 这个uid只能是int类型，可是我们大部分数据库用的id都是Long类型，有没有Long类型的方法。
下面是生成token的方法
![image](https://user-images.githubusercontent.com/47856925/61601172-da435c00-ac66-11e9-8494-6776abca43b8.png)
能帮忙看下是什么问题吗

**Comment by plutoless** [comment]
没有，目前token生成uid只支持uint32
你把其他权限都去了，只留一个kJoinChannel试试

**Comment by aberson-xie** [comment]
@plutoless 还是不行。能不能测试下BuilderTokenSample，然后更新下代码。

**Comment by plutoless** [comment]
还有expireTime是过期的绝对时间，不是相对时间
你可以先设为0

**Comment by plutoless** [comment]
代码本身应该没问题的

**Comment by aberson-xie** [comment]
@plutoless 这是原始代码。
![image](https://user-images.githubusercontent.com/47856925/61610823-c4e12880-ac8c-11e9-9081-3ef8d14f65bf.png)
默认是一天过期。
我这边各种方式都尝试了，就是黑屏，打不开视频。

**Comment by aberson-xie** [comment]
@plutoless 是因为我用的免费账户吗

**Comment by plutoless** [comment]
和免费账户无关的，你给我一个你算出来的token我看一下

**Comment by aberson-xie** [comment]
0069a9ece26f9f44b638a0a6813d39cfbb3IAD2nR4w9pUGXReeob6o3sn3/NtlTTV9NwH8JgIGQOMLpA0gao5LQvjFIgBpBXFIAAAAAAQAAQAAAAAAAgAAAAAAAwAAAAAABAAAAAAA

**Comment by aberson-xie** [comment]
0069a9ece26f9f44b638a0a6813d39cfbb3IAASyBSJ4+Xe2TPHPkvzC/4b+miw/99utXKPvt+gOoHurg0gao5LQvjFIgBldSKtLK02XQQAAQCAUQEAAgCAUQEAAwCAUQEABACAUQEA

**Comment by plutoless** [comment]
{
    "1": 86400,
    "2": 86400,
    "3": 86400,
    "4": 86400
}
这是我解出来的时间戳，依然不是绝对值

**Comment by aberson-xie** [comment]
@plutoless 可以通讯了，不过上面的代码很容易让人误解，感谢解答。
