### ISSUE TITLE
Buffer is not defined on React Native

### ISSUE THREAD

**Issue by aligoren** [AgoraIO/Tools#182]
Hi there. In the below code, react-native fires an error like "Buffer is not defined...". Because the buffer is not imported.

I think buffer should be imported on top of the file like that;

```js
import { Buffer } from 'buffer';
```

Otherwise, this library won't work on platforms that work on NodeJS such as React-Native.

https://github.com/AgoraIO/Tools/blob/2603e2055b1f9c353719deb18733036dd098546f/DynamicKey/AgoraDynamicKey/nodejs/src/AccessToken.js#L30

**Comment by yoreland** [comment]
Hi, thanks for the question.
Just curious do you mean something like React + Node + Express for backend? So far it is not covered by this demo..
If you refer to RN on client side, it is completely unsafe to generate token with client side.

**Comment by aligoren** [comment]
> Hi, thanks for the question.
> Just curious do you mean something like React + Node + Express for backend? So far it is not covered by this demo..
> If you refer to RN on client side, it is completely unsafe to generate token with client side.

Yes, it was a client-side token generation. I understand now. Thanks. I think it shouldn't be necessary on client side.
