### ISSUE TITLE
I can't record audio by agora 

### ISSUE THREAD

**Issue by tientai241102** [AgoraIO/Tools#195]
I want to record audio but I can't. I have configured the same as in the doc file but still no success.
This is my configured
<img width="853" alt="Screen Shot 2021-09-29 at 09 40 37" src="https://user-images.githubusercontent.com/72411896/135194046-048c82c4-c4e0-42f6-8315-fd218af7aea0.png">
<img width="848" alt="Screen Shot 2021-09-29 at 09 41 07" src="https://user-images.githubusercontent.com/72411896/135194053-f168f4d6-f5be-4c6e-ba98-1e0e0b798805.png">
<img width="857" alt="Screen Shot 2021-09-29 at 09 41 22" src="https://user-images.githubusercontent.com/72411896/135194058-927a9817-fb01-408c-a0f9-aaf7e89a4477.png">
.

**Comment by yoreland** [comment]
did you activate your project for cloud recording?

**Comment by tientai241102** [comment]
I think It activated
<img width="1266" alt="Screen Shot 2021-10-04 at 10 11 47" src="https://user-images.githubusercontent.com/72411896/135787650-fcea513e-516f-40cd-b50f-d2f41a0ccbd7.png">

**Comment by tientai241102** [comment]
> did you activate your project for cloud recording?

I think It activated
![image](https://user-images.githubusercontent.com/72411896/135960300-4e99c7bc-ecd5-4b5c-97f5-c83c40c245de.png)

**Comment by mahadevsempire** [comment]
Same error: 404 when stopping the recording. @tientai241102 did you find any solution?
