### ISSUE TITLE
Documentation on Privileges

### ISSUE THREAD

**Issue by toklive** [AgoraIO/Tools#204]
Is there a documentation on when / why to use the Privileges? Looking for details like when to use    kPublishAudiocdn = 5,
        kPublishVideoCdn = 6,

Also In another issue , came to know that we can't mix RTC and RTM tokens.. https://github.com/AgoraIO/Tools/issues/52, so what are the guidelines on choosing the right set of Privileges on scenarios like 1:1, Communication , Live Broadcasting, Real time messaging etc..

 public enum Privileges
    {
        kJoinChannel = 1,
        kPublishAudioStream = 2,
        kPublishVideoStream = 3,
        kPublishDataStream = 4,
        kPublishAudiocdn = 5,
        kPublishVideoCdn = 6,
        kRequestPublishAudioStream = 7,
        kRequestPublishVideoStream = 8,
        kRequestPublishDataStream = 9,
        kInvitePublishAudioStream = 10,
        kInvitePublishVideoStream = 11,
        kInvitePublishDataStream = 12,
        kAdministrateChannel = 101,
        kRtmLogin = 1000
    }

**Comment by sunshinexcode** [comment]
@toklive
you can refer to BuildRoomUserToken method of https://github.com/AgoraIO/Tools/blob/master/DynamicKey/AgoraDynamicKey/go/src/educationtokenbuilder/educationtokenbuilder.go
