### ISSUE TITLE
为啥不能在移动端设备(ios/androd)生成Token呢？

### ISSUE THREAD

**Issue by martianmartian** [AgoraIO/Tools#227]
看了一下整个Token生成的代码，貌似大部分东西可以放在移动设备上完成，而且因为这个过程比较耗费计算能力，而且要非常频繁的生成，其实更适合分布式的吧？
appID 和 certificate都可以通过app来分发，基本上是保密的，也不会丢失啥东西，所以就很不理解。

https://github.com/AgoraIO/Tools/blob/master/DynamicKey/AgoraDynamicKey/nodejs/src/AccessToken.js

请赐教

**Comment by martianmartian** [comment]
可以给一下你们测量到的 计算量消耗值 什么的衡量指标吗？就感觉这个过程比较消耗CPU，希望是我想多了


举个例子，我用下面这个方式测试，速度差别有10倍呢。。。

`javascript
const func1=function(){
  var tokenB = RtcTokenBuilder.buildTokenWithAccount(appID, appCertificate, channelName, account, role, privilegeExpiredTs);
}
const func2 = async function(){
  await redis.get("drameword");
}

const testfunc = function(func){
  var start = new Date().getTime();
  for (i = 0; i < 10000; ++i) {
    func();
  }
  var end = new Date().getTime();
  var time = end - start;
  console.log('Execution time: ' + time);
  // process.exit();
}

testfunc(func1)
initRedis().then(function(){ testfunc(func2) });
`

**Comment by plutoless** [comment]
@martianmartian appid 和 appcertificate是不应该直接分发到客户端的，因为客户端可以有各种手段反编译或解出你的appId和appcertificate，尤其是app certificate，这样相当于别人可以免费用你的账号，从安全上是非常不合适的。正确的做法是把app certificate放到服务端管理，然后由服务端分发token，这样app certificate才能确保安全

**Comment by plutoless** [comment]
> 

我不太确定您想测试什么，您是想拿我们token生成的逻辑和redis获取一个key比较性能吗? token生成本身涉及到加解密，所以相比一般操作确实会比较cpu密集，但您有很多办法(例如服务端缓存token)来避免短时间大量重复生成token，性能应该不是太大的问题才对

**Comment by martianmartian** [comment]
> @martianmartian appid 和 appcertificate是不应该直接分发到客户端的，因为客户端可以有各种手段反编译或解出你的appId和appcertificate，尤其是app certificate，这样相当于别人可以免费用你的账号，从安全上是非常不合适的。正确的做法是把app certificate放到服务端管理，然后由服务端分发token，这样app certificate才能确保安全

有道理，多谢指点

**Comment by martianmartian** [comment]
> > 
> 
> 我不太确定您想测试什么，您是想拿我们token生成的逻辑和redis获取一个key比较性能吗? token生成本身涉及到加解密，所以相比一般操作确实会比较cpu密集，但您有很多办法(例如服务端缓存token)来避免短时间大量重复生成token，性能应该不是太大的问题才对

RtcTokenBuilder.buildTokenWithAccount(appID, appCertificate, **_channelName_**, **_account_**, role, privilegeExpiredTs);

我们的应用是这样的，在线房间聊天，房间是用户临时创建的(对应channelName 参数)，每个平均约1小时有效期，每个用户(对应 account 参数)进入房间如果需要聊天，都要有token生成。很多用户喜欢在不同房间之间 跳来跳去，看过了很多个之后才决定停下来，这就导致了，生成token的频率比较高，而且因为房间是短命的，而进入房间之后又不会再频繁出来，几乎没办法有效的缓存token吧？


我希望我的逻辑那里有问题了。。。或者您有什么别的办法就太好了，请赐教啊

**Comment by martianmartian** [comment]
难道说，token可以不针对 房间内 用户id？就是说，我的后台可以定期生成一个就够了？

**Comment by plutoless** [comment]
@martianmartian 我看你写了个10000次循环，所以你的意思是你这边的qps可能达到10000? 如果是这样，你的服务肯定要能支持扩容，10000 qps也蛮夸张的，而且你可以做个redis缓存，如果同一个用户已经进过一次这个房间，在一定时间内进同一个房间他可以复用之前生成的token，只要这个token没过期，这样算下来其实qps不会很高，如果服务真的撑不住，做扩容就行了，这个算法本身是无状态的，扩容会比较容易

**Comment by plutoless** [comment]
> 难道说，token可以不针对 房间内 用户id？就是说，我的后台可以定期生成一个就够了？

如果你真的觉得这是个问题，这也是可以做到的，只要签发token的时候uid给0就可以了，这样不同用户都可以用这个token进指定的房间。但这个不建议，在安全上不是特别好，还是建议区别用户
如果你觉得进房间才拿token请求会比较频繁，你也可以在外面房间列表的时候把token随着房间列表一起返回，这样一个请求就可以把当前请求到的房间列表的token都拿到，这样可以降低请求频率

**Comment by martianmartian** [comment]
再请教个问题，appID一般是放在移动端的app里面还是每次请求token的时候一并从服务器里面获取呢？
