### ISSUE TITLE
Invalid RPM token when generated from PHP server

### ISSUE THREAD

**Issue by dennykurniawan48** [AgoraIO/Tools#228]
```
 public function enterroom(Request $request){
        $appID = MyAppId;
        $appCertificate = MyAppCerticifate;
        $channelName = "party_test";
        $user = $request->name;
        $randomString = $request->userid;
        $uid = (int)$randomString;
        $uidStr = $randomString;
        $role = RtcTokenBuilder::RoleAttendee;
        $expireTimeInSeconds = 24*3600;
        $currentTimestamp = (new DateTime("now", new DateTimeZone('UTC')))->getTimestamp();
        $privilegeExpiredTs = $currentTimestamp + $expireTimeInSeconds;

        $tokenRtcUid = RtcTokenBuilder::buildTokenWithUid($appID, $appCertificate, $channelName, $uid, $role, $privilegeExpiredTs);
        
        $tokenRtcAccount = RtcTokenBuilder::buildTokenWithUserAccount($appID, $appCertificate, $channelName, $uidStr, $role, $privilegeExpiredTs);
       
        $role = RtmTokenBuilder::RoleRtmUser;

        $tokenRtm = RtmTokenBuilder::buildToken($appID, $appCertificate, $user, $role, $privilegeExpiredTs);
        
        return response()->json(["data" => ['tokenRtcUid' => $tokenRtcUid, 'tokenRtcAccount' => $tokenRtcAccount, 'tokenRtm' => $tokenRtm]]);
    }
```
    
    This is generated Rtm token that I get from my endpoint: 0062a016160507d4146b426b9bcc36700d3IACoDIqIXB0QebMkBgjsaO42KjMFqqsP7JZHl2eTM6w9Fj5nR\/cAAAAAEABuHwAAWKMmYgEA6ANYoyZi
    
    How can I fix this? thanks in advance.

**Comment by francescodicaprio** [comment]
It looks like there is a huge bug in the `RtmTokenBuilder` class. `buildToken` method passes `$role` which is unused in it, and passes an empty string as `uid` to `AccessToken::init()`.

How the hell people have been using it during all this time!?

**Comment by dennykurniawan48** [comment]
@francescodicaprio I have no idea, but I think the problem is not in the `$role` or `$uid` because we don't need both to generate a new RTM token.

I guess the problem is a little bit more complicated.

**Comment by dennykurniawan48** [comment]
@francescodicaprio You right in [this demo](https://webdemo.agora.io/token-builder/) example we actually need Uid as a parameter, but in this example, we are using the username that is should be `$uid`

**Comment by dennykurniawan48** [comment]
Use UserID instead of username when generating RTM Token, it is working,
