### ISSUE TITLE
PHP使用SimpleTokenBuilder生成的token不能用？临时token就没问题。

### ISSUE THREAD

**Issue by yadgen** [AgoraIO/Tools#23]
客户端：Android SDK 2.3
服务器：PHP5 Or PHP7

文件：https://github.com/AgoraIO/Tools/tree/master/DynamicKey/AgoraDynamicKey/php/src
方法：SimpleTokenBuilder.php
`
$builder = new SimpleTokenBuilder($appID, $appCertificate, $channelName, $uid);
$builder->initPrivilege(SimpleTokenBuilder::Role["kRoleAdmin"]);
$token = $builder->buildToken();
`
生成的token不能用，临时token就没问题，而且发现长度也不一致。

**Comment by plutoless** [comment]
试试不要给admin的role，只给一个joinChannel的权限

**Comment by yadgen** [comment]
那这一行代码不要了？还是？怎么写的，例子上没有呀。

**Comment by yadgen** [comment]
> 试试不要给admin的role，只给一个joinChannel的权限

那这一行代码不要了？还是？怎么写的，例子上没有呀。

**Comment by plutoless** [comment]
https://github.com/AgoraIO/Tools/blob/master/DynamicKey/AgoraDynamicKey/php/sample/AccessTokenSample.php
参考这个 我们最近在对token这块做改进以确保更方便易用 这边可以先参考这个文件生成

**Comment by yadgen** [comment]
> https://github.com/AgoraIO/Tools/blob/master/DynamicKey/AgoraDynamicKey/php/sample/AccessTokenSample.php
> 参考这个 我们最近在对token这块做改进以确保更方便易用 这边可以先参考这个文件生成

你们大概什么时候更新token这块，出点详细的文档，官网没有任何通知的。

**Comment by plutoless** [comment]
代码已经更新了，文档应该也在最近，我再推进一下文档组改进

**Comment by yadgen** [comment]
> 代码已经更新了，文档应该也在最近，我再推进一下文档组改进

视频通话的token生成参考哪个？现在例子里面只有两个文件了。
https://github.com/AgoraIO/Tools/tree/master/DynamicKey/AgoraDynamicKey/php/sample

**Comment by plutoless** [comment]
用rtc就好，rtm对应我们的实时信令。我们把旧的示例都去掉了，防止干扰

**Comment by yadgen** [comment]
> 用rtc就好，rtm对应我们的实时信令。我们把旧的示例都去掉了，防止干扰

好的， 我试试看，rtc生成的token和临时token长度一致吗？

**Comment by plutoless** [comment]
长度取决于你给的权限不同，本来就不一定一致的

**Comment by yadgen** [comment]
> 长度取决于你给的权限不同，本来就不一定一致的

$expireTimeInSeconds 给0代表无限制吗？

**Comment by plutoless** [comment]
如果你需要权限永不过期，你需要把privilegeExpiredTs (默认是当前时间戳+expireTimeInSeconds) 设为0
哪怕权限设置了永不过期，token本身还是会在一天后失效，并需要生成新的token

**Comment by yadgen** [comment]
> 如果你需要权限永不过期，你需要把privilegeExpiredTs (默认是当前时间戳+expireTimeInSeconds) 设为0
> 哪怕权限设置了永不过期，token本身还是会在一天后失效，并需要生成新的token

buildTokenWithUid和buildTokenWithUserAccount，两个方法生成的token均可以使用吧？

https://github.com/AgoraIO/Tools/blob/master/DynamicKey/AgoraDynamicKey/php/src/RtcTokenBuilder.php
这个文件很多错误。
46，47，48，RoleAttendee常量名字写错了，PHP应该用冒号（:）。

**Comment by plutoless** [comment]
是有问题，之前执行没看到错误，更新一下再试试？

**Comment by plutoless** [comment]
两个方法对应我们sdk的int uid和string uid，都可以用的

**Comment by yadgen** [comment]
> 两个方法对应我们sdk的int uid和string uid，都可以用的

https://github.com/AgoraIO/Tools/blob/master/DynamicKey/AgoraDynamicKey/php/src/RtcTokenBuilder.php
43行，AccessToken类，init并不是静态函数，无法使用冒号（:）调用，得先new一个实例出来。

**Comment by plutoless** [comment]
感谢 您说得对，已经调整了，这个方法确实是静态方法
我这边之前执行也没报错所以没发现，还有别的意见这边可以尽管提

**Comment by yadgen** [comment]
> 感谢 您说得对，已经调整了，这个方法确实是静态方法
> 我这边之前执行也没报错所以没发现，还有别的意见这边可以尽管提

目前没有发现其他问题，我这边先测试下Android SDK 2.3.2视频通话是否有问题。

**Comment by yadgen** [comment]
> 感谢 您说得对，已经调整了，这个方法确实是静态方法
> 我这边之前执行也没报错所以没发现，还有别的意见这边可以尽管提

`
006db1976452bfc4712a42607967ca1aa74IABRD8IK80exzDnX3R6vIyFDxGVYjvdi/pCPZBlnRmCjKJ6k2ieHVhO7IgApVwEArsZHXQQAAQAAAAAAAwAAAAAAAgAAAAAABAAAAAAA
`
这是我生成的token，为什么告诉我无效呢？

**Comment by plutoless** [comment]
uid和频道名都和生成token时候的参数一致吗？我刚自己试了下是可以的

**Comment by yadgen** [comment]
> uid和频道名都和生成token时候的参数一致吗？我刚自己试了下是可以的

比如
发起方
`
uid=1
channel_id=1564898606100193903
token=006db1976452bfc4712a42607967ca1aa74IABRD8IK80exzDnX3R6vIyFDxGVYjvdi/pCPZBlnRmCjKJ6k2ieHVhO7IgApVwEArsZHXQQAAQAAAAAAAwAAAAAAAgAAAAAABAAAAAAA
`
接收方
`
uid=2
channel_id=1564898606100193903
token=006db1976452bfc4712a42607967ca1aa74IABRD8IK80exzDnX3R6vIyFDxGVYjvdi/pCPZBlnRmCjKJ6k2ieHVhO7IgApVwEArsZHXQQAAQAAAAAAAwAAAAAAAgAAAAAABAAAAAAA
`

只是uid不通，android端使用token加入频道时，声网返回的信息。

**Comment by plutoless** [comment]
您生成token的示例里有个参数是uid，这个uid若给非0的值的情况，生成的token只有这个uid的用户可以使用的。
不想检查uid的情况，可以将uid置为0，则任何uid的用户都可以用这个token加入这个频道。dashboard生成的临时token就是这样的token

**Comment by yadgen** [comment]
> 您生成token的示例里有个参数是uid，这个uid若给非0的值的情况，生成的token只有这个uid的用户可以使用的。
> 不想检查uid的情况，可以将uid置为0，则任何uid的用户都可以用这个token加入这个频道。dashboard生成的临时token就是这样的token

可以了，谢谢。
