### ISSUE TITLE
Android个别手机接通视频时，会出现一边黑屏有声音，一边正常画面有声音，这是为什么

### ISSUE THREAD

**Issue by niejunfeng1234** [AgoraIO/Tools#24]

**Comment by plutoless** [comment]
必现吗？

**Comment by plutoless** [comment]
给下复现的手机型号和日志？

**Comment by niejunfeng1234** [comment]
闭现，我pad和pad连接没问题，两个都能看到画面和声音，但是一个pad和一个手机，或者一个手机和另外一个手机也不行

**Comment by niejunfeng1234** [comment]
日志从哪里拿？手机是mix2   系统版本是android7.1.1

**Comment by plutoless** [comment]
可以先给我个你复现黑屏的时间和频道名我看下后台

**Comment by niejunfeng1234** [comment]
就刚刚，频道号1564905180100194710，token：006db1976452bfc4712a42607967ca1aa74IABcZcbVz71+t6ZjExKUYea5HunoWZugxMc2939gMDaRBo3tRaMAAAAAIgAU9wAAXOBHXQQAAQAAAAAAAwAAAAAAAgAAAAAABAAAAAAA，
uid是传的0

**Comment by niejunfeng1234** [comment]
你好，怎么样了

**Comment by plutoless** [comment]
看了一下，确实有一台设备收到了数据但没有解码出视频，这边可以把黑屏的手机日志发一下吗？
设置SDK日志路径的方法https://docs.agora.io/cn/Voice/API%20Reference/oc/Classes/AgoraRtcEngineKit.html#//api/name/setLogFile:
