### ISSUE TITLE
need RtcTokenBuilder in dart 

### ISSUE THREAD

**Issue by osamamohammed98** [AgoraIO/Tools#240]
we need this to create token

**Comment by plutoless** [comment]
@osamamohammed98 why do you need this? token should usually be generated on server side

**Comment by osamamohammed98** [comment]
Yes i make it and forget to close

**Comment by VtorovN** [comment]
@plutoless, hello!

I'm currently writing server-side code in Dart using [Serverpod](https://github.com/serverpod/serverpod). It might become popular some day. Would you consider creating Dart implementation of the token builder?
