### ISSUE TITLE
Java SDK 1.6.1 版提示 'modelVersion' must be one of [4.0.0] but is '1.6.1'

### ISSUE THREAD

**Issue by DevDengChao** [AgoraIO/Tools#242]
```log
Errors occurred while build effective model from C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.agora\authentication\1.6.1\1cef08bd181f6592589f1c9570a886b863d924fd\authentication-1.6.1.pom:
    'modelVersion' must be one of [4.0.0] but is '1.6.1'. in io.agora:authentication:1.6.1
```

检查 authentication-1.6.1.pom 后发现 modelVersion 字段的值是 1.6.1 , 但 Maven 建议 modelVersion 应当设置为 4.0.0 .

参考: https://maven.apache.org/guides/introduction/introduction-to-the-pom.html#minimal-pom :
> `modelVersion` - should be set to 4.0.0

**Comment by sunshinexcode** [comment]
@DevDengChao 
查看了https://github.com/AgoraIO/Tools/blob/master/DynamicKey/AgoraDynamicKey/java/pom.xml, modelVersion设置的是4.0.0, 值是1.6.1是否是集成使用上进行了修改导致, 再查看确认下

**Comment by DevDengChao** [comment]
好像是 Spring boot 插件的问题, 新建空白的 Gradle 工程并依赖的话不会有提示, 但是新建的 Spring boot Gradle 工程并依赖的话就会有这样的提示.

你可以试试在这个示例工程里运行 `gradle :compileJava`: [demo.zip](https://github.com/AgoraIO/Tools/files/8842350/demo.zip)
