### ISSUE TITLE
csharp测试工程生成的token不在有效期，方法调用把channalName弄丢了，而且示例参数值都不能代表他的含义也没有注释，较难理解

### ISSUE THREAD

**Issue by xhj0307** [AgoraIO/Tools#245]
通过csharp demo提供的方式获得RTCToken显示时间过期或者DYNAMIC_KEY_EXPIRED 获取RTMToken显示Error Code 5 - Signature verification failed.

**Comment by sunshinexcode** [comment]
新增RTC ut test, PR https://github.com/AgoraIO/Tools/pull/246, 已合并.
代码: https://github.com/AgoraIO/Tools/blob/master/DynamicKey/AgoraDynamicKey/csharp/test/AgoraIO.Tests/RtcTokenTest.cs

调整appId/appCertificate值生成token, 通过以下工具验证
https://webdemo.agora.io/agora-web-showcase/examples/Agora-Web-Tutorial-1to1-Web/

**Comment by xhj0307** [comment]
收到，感谢。
