### ISSUE TITLE
Vapor(Swift based server) RTCTokenBuilder , building token with Swift

### ISSUE THREAD

**Issue by nitsanasraf** [AgoraIO/Tools#256]
Hey, I am trying to generate a token in my server that I can send to the iOS Client, I am using Vapor 4, which is a Swift-based backend web framework, and I cannot find a way to build the token using swift. I only see ways to do that with other languages, like go, c++, c#, java, js, and so on.

Is there a way to build the token using Swift? 
for example in python you would do something like that:
`token = RtcTokenBuilder.buildTokenWithUid(appId, appCertificate, channelName, uid, role, privilegeExpiredTs)
`
how would I achieve this with swift?

**Comment by plutoless** [comment]
There's no swift implementation for now.
Can swift server somehow use the c++ api? if yes maybe you can use the c++ version..

**Comment by nitsanasraf** [comment]
Okay thank you, I've managed to fix it by using the python implementation, and calling the required function from a swift file.
