### ISSUE TITLE
Is there a way to test connections to channels on a web demo by account ?

### ISSUE THREAD

**Issue by nitsanasraf** [AgoraIO/Tools#258]
I know you can test connections with a uid, but is there a way to test connections with a user id string?
what I mean is that here:
https://webdemo.agora.io/basicVideoCall/index.html
you can only test it if your token is being generated with a uid, in my case I generate it with a user account, someone knows any alternative demo to test it ?

**Comment by plutoless** [comment]
by default our sdk is using integer uid, same for tokens. i don't think we provide apis to generate token with string account. where did you see it?

**Comment by nitsanasraf** [comment]
@plutoless In python3 - RtcTokenBuilder :
There are 2 functions , one is  `buildTokenWithUid`
And one is `buildTokenWithAccount` Which should accept a string instead of a UInt32, which I use:
   ` def buildTokenWithAccount(appId, appCertificate, channelName, account, role, privilegeExpiredTs):`

The `account` Parameter is basically a string User ID isn’t it ?

**Comment by nitsanasraf** [comment]
@plutoless https://docs.agora.io/en/All/faq/string

**Comment by gwhizoftv** [comment]
There is massive confusion in the Agora docs and conflicting requirements
between different Agora services over when string UIDs and when Int UIDs
can be used. It is frankly a real mess. FOr now be very very sure that you
won't need and services limited to Int UIDs if you decide to go for string
UIDs.

**Comment by nitsanasraf** [comment]
Thank you, I'm just gonna stick to uint UIDs instead of strings UIDs for now..
