### ISSUE TITLE
您好，使用nodejs生成器用uid生成token无效

### ISSUE THREAD

**Issue by xhj0307** [AgoraIO/Tools#260]
RtcTokenBuilderSample.js运行生成的token在webDEMO中提示无效，无授权，是不是出了一些问题，和uid或者频道名不匹配了？核对了两次，两台电脑都测试了，皆是无法使用。

**Comment by sunshinexcode** [comment]
appID和appCertificate替换成你自己的, 再尝试一下

RTC demo测试使用https://webdemo.agora.io/agora-web-showcase/examples/Agora-Web-Tutorial-1to1-Web/
注意: 需要填写UID

<img width="417" alt="image" src="https://user-images.githubusercontent.com/5187981/185046019-ea115acb-3812-460d-8cfd-d352c9da45ba.png">
