### ISSUE TITLE
Are there plans to support rust

### ISSUE THREAD

**Issue by JunaYa** [AgoraIO/Tools#262]
When will rust be supported, rust is also very popular right now。

**Comment by sunshinexcode** [comment]
Expected 2022 Q4 supported

**Comment by DerPlayer2001** [comment]
Is there any progress on Rust support?
Especially for the token builder. Since the Token builder is pretty simple is it possible to contribute?

**Comment by plutoless** [comment]
hi @DerPlayer2001 your PR would be greatly appreciated. you can fork the repo and open a PR if possible.

**Comment by sunshinexcode** [comment]
@DerPlayer2001 
Currently, the token for the Rust programming language is supported. Please refer to https://github.com/AgoraIO/Tools/tree/master/DynamicKey/AgoraDynamicKey/rust for more information. The integration is done through source code integration.
