### ISSUE TITLE
C# RTM token expiration date does not affect the token

### ISSUE THREAD

**Issue by moneer-muntazah** [AgoraIO/Tools#265]
In C# if you call `RtmTokenBuilder.buildToken` with a low expireation time like `RtmTokenBuilder.buildToken(appId, appCertificate, appointment.PatientId, 12);` The use can still login and send messages

Also in Utils.cs

```
public static int getTimestamp()
        {
            TimeSpan t = DateTime.UtcNow - new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
            return (int)t.TotalSeconds;
        }
```

should account for timezone ` DateTime.UtcNow - new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc)`

**Comment by sunshinexcode** [comment]
fixed in PR https://github.com/AgoraIO/Tools/pull/273
thanks.

**Comment by moneer-muntazah** [comment]
@sunshinexcode please check the first part of  the issue. When I use the C# version to generate an RTM token with an old/expired unix time, I can use the token to login and send messages. If I use the same uinx time with the nodejs version I get a longer token that disallows me to join. 

I noticed that the nodejs version factors in the role in the token. Maybe that has something to do with it. 

I used flutter to test this.
