### ISSUE TITLE
buildTokenWithAccount returning same token even after expiration

### ISSUE THREAD

**Issue by smallzZz8** [AgoraIO/Tools#278]
So I am trying to generate a token with buildTokenWithAccount with a 60 second expiration time and it returns a valid token. However after the 60 seconds, if I recall the function and it is returning the same token it created the first time. Is this function suppose to return a different token after the original expiration time?

```
const appId = process.env.AGORA_APP_ID || ''
const appCertificate = process.env.AGORA_APP_CERTIFICATE || ''
const role = RtcRole.PUBLISHER

const expirationTimeInSeconds = 60
const currentTimestamp = Math.floor(Date.now() / 1000)
const privilegeExpiredTs = currentTimestamp + expirationTimeInSeconds

const userToken = RtcTokenBuilder.buildTokenWithAccount(
            appId,
            appCertificate,
            data.channelId,
            data.customUserId,
            role,
            privilegeExpiredTs
        )
```

**Comment by plutoless** [comment]
it should. because currentTimestamp will change for your second execution. this will lead to privilegeExpreiedTs change which leads to a different token generated.

**Comment by smallzZz8** [comment]
Ah so I have found the solution based off of your reply. Basically I had privilegeExpiredTs defined at the top of my file which when deployed would only get ran once causing all my privilegeExpiredTs to be the same. Moving that logic into the function itself causes a new timestamp to be made each time which in return creates a new token each time. Thanks!
