### ISSUE TITLE
Update README with Python Token Server for Agora Chat

### ISSUE THREAD

**Issue by Catherinesjkim** [AgoraIO/Tools#288]
You currently have a Python token server for Agora Chat but your README doesn't indicate that. 

Please update. Thanks!

![ChatPyTokenServer](https://user-images.githubusercontent.com/17114008/194104052-f1ad3b71-5cef-4fc9-8d48-474ef02859ff.png)

**Comment by sunshinexcode** [comment]
We will add the relevant instructions as soon as possible

**Comment by sunshinexcode** [comment]
You can refer to https://docs.agora.io/en/agora-chat/develop/generate-user-tokens
