### ISSUE TITLE
Client keeps disconnecting from Agora Chat server after opening connection with token and username

### ISSUE THREAD

**Issue by Chris-CWZ** [AgoraIO/Tools#302]
I have successfully generated a User Token on my backend and passed it to client. Client uses Agora Username and said User Token to open connection with Agora Chat Server. After connection, it returns a ChatToken(access_token which I dont even know what its supposed to be used for). But after a few seconds, it disconnects from the server. This happens every single time and causes me to be unable to send any messages since it says User not login(error code 39)

**Comment by sunshinexcode** [comment]
It is recommended to check the expired time of the token

**Comment by Mr-Dead-Rabbit** [comment]
It seems to be an issue with token expire setting. @Chris-CWZ 
Maybe you can set a long expire time from your backend, 
You can refer to this setting [https://github.com/AgoraIO/Agora-Chat-API-Examples/blob/main/chat-app-server/src/main/resources/application.properties](url)

**Comment by Chris-CWZ** [comment]
Thanks for the feedback, I've already set the expiry time to be 86400 seconds as per the documentation, but the issue is still there. I've reported this issue via a ticket on the Agora platform, and they've escalated this issue to Tier 2. Seems like a bug on their end, and they're fixing it
