### ISSUE TITLE
[nodejs] nodeunit package should be a dev dependency

### ISSUE THREAD

**Issue by eungkyu** [AgoraIO/Tools#304]
If I add npm package agora-access-token, there are too many dependencies installed then expected.
This is because it has nodeunit as dependency.

nodeunit package should be a dev dependency because it is only for testing.

Then, dependency packages will reduce to 7 packages from 100+ packages.

**Comment by sunshinexcode** [comment]
Please use agora-token instead. agora-access-token has been deprecated.

https://www.npmjs.com/package/agora-token
npm i agora-token

**Comment by hyrious** [comment]
@sunshinexcode agora-token still has this problem. In fact, as a workaround, we did this: https://github.com/AgoraIO-Extensions/agora-rtc-react/blob/f4871f4ef21f09ca8ed0d58d37f2e0e8f7e1f4c5/package.json#L74-L77

**Comment by sunshinexcode** [comment]
@hyrious  Released version 2.0.3 and moved nodeunit to devDependencies.
