### ISSUE TITLE
[C# / CSharp] Version 007 is missing

### ISSUE THREAD

**Issue by XeroDays** [AgoraIO/Tools#308]
The C# Package with `RtcTokenTest` it has the old version token..

Comparing both : 
Actual : `006f3f302a729ad4d29bfa3e6f7d8e4d0ebIABgoiohiaxEFehiXryTvrI9wFLtrDCe4F8yTE1DkyX2kBw69csh39v0IgAWFoId/Y2TYwQAAQCNSpJjAgCNSpJjAwCNSpJjBACNSpJj`

Expected:
`007eJxTYHg8Xf2D5KnZOzeofHLjefepJ3zrgT2vXwR6zlFJ2viis3WCAkOacZqxgVGiuZFlYopJipFlUlqicapZmnmKRapJikFq0j23SckNgYwMuwM6mBgZIBDEZ2UwNDI2MWVgAACKmiK4`

**Comment by Corvus-inc** [comment]
I have the same problem. 
In Agora Console generated:
007eJxTYAi58F1qpqGI7K8un8zPxvcSip6Hswuvdnk+d8UTrt/5m/4oMJiZGZolGaekmCQaWZiYplgkGiUmmxiaGpsbpJiam5mbX/o9PbkhkJGhOV2aiZEBAkF8Ngbn/KKy0mIGBgDQUyEq
In C#  tools:
0066616b3dd4a2845d8a2ac415370d57677IADXyonmqaCXhd9K1MYfGyreotrYBtJ7h02VqoT/zGyVjD3oYinSY0iIEAByiNwOv1SZYwEAAQAQDgAA

**Comment by XeroDays** [comment]
@Corvus-inc You  can use the php version. its working fine for now... Use it as temporary..

**Comment by Corvus-inc** [comment]
> @Corvus-inc You can use the php version. its working fine for now... Use it as temporary..

Thanks. We used Next.JS one. This works fine. But we want to make it on C# and resolve the problem.

**Comment by sonetony** [comment]
Hi, I am also facing the same issue. 3 months past, but still no 007 C# AccessToken2.
Please help to release updated rtcTokenBuilder2 for C#.
Or at least provide a release date?

**Comment by plutoless** [comment]
hi guys we are sorry but currently we don't have resource to add C# AccessToken2. Please find other alternate languages to generate your token. The original 006 AccessToken was added by a community developer so if any help like a PR would also be greatly appreciated.

**Comment by XeroDays** [comment]
Dear @plutoless  add me into the collaborators, i will try my best work on as soon as I get time.

**Comment by plutoless** [comment]
hi @XeroDays appreciated, that would be great help. You may just fork the repo and raise a PR from your forked repo to ours. I will help process and merge it ASAP.

**Comment by XeroDays** [comment]
Okay, Thanks!

**Comment by ips-jm** [comment]
Any news on this?

**Comment by sunshinexcode** [comment]
The version 007 of C# has already been provided.
https://github.com/AgoraIO/Tools/tree/master/DynamicKey/AgoraDynamicKey/csharp/src/AgoraIO/TokenBuilders
