### ISSUE TITLE
 Is it mandatory to login RTC while fetching Video/Audio in Android App?

### ISSUE THREAD

**Issue by ruchikri01** [AgoraIO/Tools#315]
Problem Statement - I have an application where I used agora for live streaming. Now, I want to fetch the video outside the class and show in a grid. So, Is it mandatory to login to Agora RTC while fetching Video/Audio in Android App?

**Comment by plutoless** [comment]
i guess while you are saying "login" you mean join channel with token.
if you want to fetch video/audio you will have to join a channel, this is mandatory.
however, if you don't want security you can choose to turn off token feature, then anyone knowing your appid can join channel and fetch the stream freely - while this can lead to malicious actions stealing your usage amount so it's not recommended.
