### ISSUE TITLE
NO_AUTHORIZED error

### ISSUE THREAD

**Issue by IG-88-2** [AgoraIO/Tools#32]
Hello i'm trying to use nodejs package to generate token for agora service, when i'm trying with values from example it works fine, in particular when property user id filled with value 2882341273 i receive succesfull response (token generated correctly), but when i'm trying to switch to usage of ids from our own database it creates an issue (you can see example error below):

backend.js:1 10:05:49:744 Agora-SDK [ERROR]: [5D242] Get server node failed [NO_AUTHORIZED] https://webrtc2-ap-web-1.agora.io/api/v1 NO_AUTHORIZED

This is value that supplied instead of mentioned above a number:

0|main     | 24-09-2019 03:05:47.860 36384 info: [agoraToken] uid 5d2a9678af39ea5d7d1855ba

Please let me know if you have any suggestions on how this problem can be avoided. Appreciate your work. Thank you.

**Comment by plutoless** [comment]
so it works with int uid but not string uid?

**Comment by IG-88-2** [comment]
yes so basically when im replacing it to be string (uuid) it throws this error, when im chaning it back to number it fine again, what do you think could be the cause ?

**Comment by dongsettle** [comment]
Web sdk 2.9.0 version has a known bug that will cause the token generated by string uid Unable to join channel successfully, the error message is NO_AUTHORIZED, we will fix this problem in the next version of sdk, you may need to use int uid temporarily To generate tokens to circumvent this problem, or you can use version 2.8.0 sdk

**Comment by specc** [comment]
would be helpful if you can provide a link to 2.8.0 web sdk. I had to guess the link to download that version. All of your sdk download links point to the newest download.

**Comment by dongsettle** [comment]
cdn link:  https://cdn.agora.io/sdk/release/AgoraRTCSDK-2.8.0.js
download link: http://download.agora.io/sdk/release/Agora_Web_SDK_v2_8_0_FULL.zip

**Comment by kush3107** [comment]
I am getting this issue with version 3.0.0 also.

**Comment by plutoless** [comment]
@kush3107  please provide more details, you may have a real NO_AUTHORIZE issue.

**Comment by kush3107** [comment]
@plutoless  I am using the same code from node samples to create the Dynamic Key.

```
app.get('/tt', [], (req: express.Request, res: express.Response) => {
    // Rtc Examples
    const appID = 'c3208e8e85b5499f89*********';
    const appCertificate = 'ce75e73599df48cbb15c*******';
    const channelName = 'popo123';
    const uid = 2882341273;
    const account = "2882341273";
    const role = RtcRole.PUBLISHER;

    const expirationTimeInSeconds = 3600;

    const currentTimestamp = Math.floor(Date.now() / 1000);

    const privilegeExpiredTs = currentTimestamp + expirationTimeInSeconds;

// IMPORTANT! Build token with either the uid or with the user account. Comment out the option you do not want to use below.

    const tokenA = RtcTokenBuilder.buildTokenWithUid(appID, appCertificate, channelName, uid, role, privilegeExpiredTs);
    console.log("Token With Integer Number Uid: " + tokenA);

// Build token with user account
    const tokenB = RtcTokenBuilder.buildTokenWithAccount(appID, appCertificate, channelName, account, role, privilegeExpiredTs);
    console.log("Token With UserAccount: " + tokenB);

    res.json({
        token: tokenA
    });
});
```

Broadcasting and joining the channel one are also the same code from the samples and they use the same app id and the token generated from the above the code.

Using [this](https://github.com/AgoraIO/Basic-Video-Broadcasting/tree/master/OpenLive-Web) for broadcasting and [this](https://github.com/AgoraIO/Basic-Video-Call/tree/master/One-to-One-Video/Agora-Web-Tutorial-1to1-React) for joining the channel and receiving the stream

**Comment by specc** [comment]
> I am getting this issue with version 3.0.0 also.

If I were you, stick with 2.8.0 I also found that after you are able to join with string as uid, there are other problems like subscriber event not triggering. Just stick with interger uid for now until they fix the issue.

**Comment by kush3107** [comment]
@specc I tried it with web sdk 2.8.0 also.

**Comment by kush3107** [comment]
@specc Also the I am getting the same token with both methods on the node server.

**Comment by plutoless** [comment]
@kush3107  it seems you are using a fixed uid 2882341273 and channel popo123 when calculating token. you need to ensure you are joining the same channel with same uid. The two repository you mentioned by default will use 0 as uid to join channel which means it will use a random uid.

**Comment by kush3107** [comment]
@plutoless Ok thanks for the direction. I will double check it on my end

**Comment by kush3107** [comment]
Hi @plutoless The stream is now broadcasting for me, thanks for the help but now when I try to connect using [this](https://github.com/AgoraIO/Basic-Video-Call/tree/master/One-to-One-Video/Agora-Web-Tutorial-1to1-React) I cannot see the remote stream all I see is the local stream. Please tell me what details you need.

 Thanks for the help in advance.

**Comment by specc** [comment]
> Hi @plutoless The stream is now broadcasting for me, thanks for the help but now when I try to connect using [this](https://github.com/AgoraIO/Basic-Video-Call/tree/master/One-to-One-Video/Agora-Web-Tutorial-1to1-React) I cannot see the remote stream all I see is the local stream. Please tell me what details you need.
> 
> Thanks for the help in advance.

Like i said even if you are able to connect, the subscription event wont be triggered. You should use uid as integer then it should work.

**Comment by kush3107** [comment]
@specc I am using uid as integer and moreover I get the same value for `tokenA` or `tokenB` from the nodejs example. Also I am using `"agora-rtc-sdk": "2.8.0"` but still cannot see the remote stream on the one-to-one video example and this works fine when I use the token generated from agora console.

**Comment by plutoless** [comment]
just to clarify, you have two clients joining the same channel, and you won't be able to see each other? could you pls share the channel name and corresponding uid, plus your join channel time so that i can check backend?

**Comment by kush3107** [comment]
@plutoless 

App Name on my account - new
App Id - c3208e8e85b5499f897db9d83f1b6f75
App Certificate - ce75e73599df48cbb15ca02abc1b6c10
Channel Name - popo123
UID - 2882341273
Expired Time - current timestamp + 3600s

**Comment by kush3107** [comment]
@plutoless The strange thing is that when I try to do this with the temp token generated from agora console everything works fine.

**Comment by plutoless** [comment]
@kush3107  i checked few backend cases and 2882341273 is the only user joined in channel. if you want to see remote stream you will need another client joining same channel.

**Comment by kush3107** [comment]
Hi @plutoless Thanks for all the help. I figured out the issue. I was using the same token for both users.

**Comment by tayoraph** [comment]
hi guys , please help. i m building a live broadcast with angular , was able to generate a token successfully from the host , but i m finding subscribing to the stream difficult . it is giving same issue NO_AUTHORIZE. My uid is integer

**Comment by tabish-ahmed** [comment]
I am also getting the same error @tayoraph

**Comment by tayoraph** [comment]
try build your app in prod mode a = to see that crypto compiles . I noticed
crytpo wasn't compiling so it was generating a false token kinda. Though i
haven't tried with token after compiling successfully in prod mode. I'm
currently using it without token

**Comment by shuvro** [comment]
I am using this https://webdemo.agora.io/agora-web-showcase/examples/Agora-Web-Tutorial-1to1-Web/
to test. But it shows that NO_AUTHORISATION error.

**Comment by spektra2147** [comment]
In this UI, need to pass UID which are available in the ADVANCED SETTINGS

**Comment by hkmsadek** [comment]
I am facing the same issue.. 

```
 const uid : number = 1235643434344;
  const role = RtcRole.PUBLISHER;
  const expirationTimeInSeconds = 3600
  const currentTimestamp = Math.floor(Date.now() / 1000)
  const privilegeExpiredTs = currentTimestamp + expirationTimeInSeconds
  const token = RtcTokenBuilder.buildTokenWithUid(appID, appCertificate, channelName, uid, role, privilegeExpiredTs);
```

And I am using same chanel name, uid and app id in frontend but getting `agora-rtc-client.js?ea71:35 client join failed NO_AUTHORIZED`

I am using vue.js sample code and it has package installed ` "agora-rtc-sdk": "^3.1.1",`

Any help?
