### ISSUE TITLE
RTC token not valid

### ISSUE THREAD

**Issue by M-Mykola** [AgoraIO/Tools#320]
Hello everyone!
I try to generate RTC token for video/voice call.
![image](https://user-images.githubusercontent.com/84658438/215548729-296515da-6c2e-4423-a536-2ec79f0b793b.png)
![image](https://user-images.githubusercontent.com/84658438/215548900-d32265c1-bbcd-4fae-9c69-6e380243e97a.png)
![image](https://user-images.githubusercontent.com/84658438/215548998-14744ac2-8537-4d4f-a007-563cd9d7373b.png)
I hardcoded the value to the function to test it, but still dont work, still I have issue!Anyone have any idea why it work like this?

**Comment by plutoless** [comment]
hi @M-Mykola try using Date().getTime() + expirationSeconds.

**Comment by M-Mykola** [comment]
Hey, I find a problem, was on the uid. uid not need to get from agora, like I think, need to generate or, agora create you uuid(only number value), documentation not was understandable.

**Comment by plutoless** [comment]
@M-Mykola seems to be designed behavior. what do you want agora to improve?
