### ISSUE TITLE
Which package should I use? when it cames to agora-access-token and agora-token.

### ISSUE THREAD

**Issue by ycj3** [AgoraIO/Tools#324]
When I use agora token , there are two npm package agora-access-token and agora-token. 

Which package should I use?

**Comment by sunshinexcode** [comment]
please use agora-token, https://www.npmjs.com/package/agora-token

**Comment by MariamShalan** [comment]
> please use agora-token, https://www.npmjs.com/package/agora-token

what's the difference between them? plus it has like 8 security vulnerabilities

**Comment by plutoless** [comment]
@MariamShalan agora-access-token is an old npm package published before. it's now deprecated.
