### ISSUE TITLE
[ruby] warning message of dynamic_key5.rb in Ruby 3.2

### ISSUE THREAD

**Issue by cou929** [AgoraIO/Tools#326]
I've received the following warning message when running `dynamic_key5.rb` in Ruby 3.2.1. 
(I understand that the `Dynamic Key` is for the older versions, but I'm using it in our existing production environment.)

```ruby
<internal:pack>:8: warning: unknown pack directive '<' in '<S'
```

The corresponding lines can be found [here](https://github.com/AgoraIO/Tools/blob/127831aa0f5ddab4aeec31d7ce2c06b191b64294/DynamicKey/AgoraDynamicKey/ruby/src/dynamic_key5.rb#L167-L177).

```ruby
  def pack_uint16(x)
    [x].pack('<S')
  end

  def pack_uint32(x)
    [x].pack('<I')
  end

  def pack_int32(x)
    [x].pack('<i')
  end
```

- According to the [Array#pack's document (for at least Ruby 2.5+)](https://docs.ruby-lang.org/en/2.5.0/Array.html#method-i-pack), the `<` directive should be placed after `S`, `I` or `i`.
- Currently, the `<` directive seems to be ignored and the endian is selected based on the architecture where the script is running.
- It seems that this warning message has been shown since Ruby 3.2

Therefore, my question is: was the original intention of `pack_xxx` methods enforcing the little-endian? If so, would it be correct to replace `<S` or others with `S<` and so on?

**Comment by plutoless** [comment]
we can't find the original ruby author any more but ... yes you are right the intention is to enforcing little-endian.

**Comment by cou929** [comment]
Thank you for your confirmation 👍 
I created a pull request that fixes this.

https://github.com/AgoraIO/Tools/pull/327

**Comment by plutoless** [comment]
thank you for your contribution! i have merged the PR.
