### ISSUE TITLE
feat: Support for ESM

### ISSUE THREAD

**Issue by EkaanshArora** [AgoraIO/Tools#328]
### Can we add support for ESM for [agora-token](https://www.npmjs.com/package/agora-token)?

ECMAScript modules are [the official standard format](https://tc39.github.io/ecma262/#sec-modules) to package JavaScript code for reuse. Modules are defined using a variety of [import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) and [export](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export) statements.

Node.js fully supports ECMAScript modules as they are currently specified and provides interoperability between them and its original module format, [CommonJS](https://nodejs.org/api/modules.html).

Newer build tools like Vite expect libraries to support ESM exports. Not having ESM and only exporting to CJS, needs a workaround to use the library like so:
```js
import TokenServerImport from 'agora-token';
const { RtcRole, RtcTokenBuilder } = TokenServerImport; // CJS module import
```
Using a named import from the package might work in dev, but would break in production builds:
![image](https://user-images.githubusercontent.com/10047883/229123666-3e412b20-0d13-4cea-93ae-7806bde360fd.png)

**Comment by EkaanshArora** [comment]
Hey @plutoless what are your thoughts?

**Comment by sunshinexcode** [comment]
@EkaanshArora 
Can you provide the error message in production builds?

**Comment by sunshinexcode** [comment]
@EkaanshArora 
Set the type of package.json to module, and try again
