### ISSUE TITLE
JAVA使用RtcTokenBuilder产生token无法使用

### ISSUE THREAD

**Issue by Leo-LiJun** [AgoraIO/Tools#33]
如题

**Comment by Leo-LiJun** [comment]
AgoraRTC.js:2 18:23:13:459 Agora-SDK [ERROR]: [23EF4] User join failed [ERR_NO_AUTHORIZED]
使用H5端测试出现该错误

**Comment by plutoless** [comment]
生成的方式可以发我看一下吗

**Comment by Leo-LiJun** [comment]
`使用的就是提供的例子，H5的版本是v2.8.0`

`public class RtcTokenBuilderSample {
    static String appId = "";
    static String appCertificate = "";
    static String channelName = "7d72365eb983485397e3e3f9d460bdda";
    static String userAccount = "2082341273";
    static int uid = 2082341273;
    static int expirationTimeInSeconds = 3600; 

    public static void main(String[] args) throws Exception {
        RtcTokenBuilder token = new RtcTokenBuilder();
        int timestamp = (int)(System.currentTimeMillis() / 1000 + expirationTimeInSeconds);
        String result = token.buildTokenWithUserAccount(appId, appCertificate,  
        		 channelName, userAccount, Role.Role_Publisher, timestamp);
        System.out.println(result);
        
        result = token.buildTokenWithUid(appId, appCertificate,  
       		 channelName, uid, Role.Role_Publisher, timestamp);
        System.out.println(result);
    }
}`

**Comment by plutoless** [comment]
@Leo-LiJun  你加入频道的时候，uid指定的也是2082341273 吗？

**Comment by plutoless** [comment]
加入的频道也是7d72365eb983485397e3e3f9d460bdda 吗？

**Comment by Leo-LiJun** [comment]
是的，临时的token可以。

**Comment by Leo-LiJun** [comment]
@plutoless 是否有实时交流反馈的群或者账号？

**Comment by plutoless** [comment]
@Leo-LiJun 你可以找一下客户支持，可以的话初始化sdk和加入频道的代码也发一下

**Comment by Leo-LiJun** [comment]
@plutoless 这边使用的都是直接从官网下载的例子，H5是之前官网下载的没改过，生成token是直接用github上下载的，然后修改appId和appCertificate进行生成token.

**Comment by plutoless** [comment]
@Leo-LiJun  能不能用java算个token发我下？

**Comment by Leo-LiJun** [comment]
@plutoless 006bc7e6869bc2d4381aaa07aab711f123dIADpI6sjb9fqRfBwESh3HOMC9qgPWg0qIGRXbAOK61X7F7dIfRBPAoleIgD8vemj23mmXQQAAQBrNqVdAgBrNqVdAwBrNqVdBABrNqVd

**Comment by plutoless** [comment]
@Leo-LiJun 不好意思回复晚了，我们尽快调查一下，尽快给您结论

**Comment by plutoless** [comment]
https://github.com/AgoraIO/Tools/pull/34 @Leo-LiJun
