### ISSUE TITLE
Why c# code is using _uid as _channelName RTM Token generation c#

### ISSUE THREAD

**Issue by Harsh-U-Joshi** [AgoraIO/Tools#332]
In Repository code for [C#](https://github.com/AgoraIO/Tools/tree/master/DynamicKey/AgoraDynamicKey/csharp)
[RtmTokenTest](https://github.com/AgoraIO/Tools/blob/master/DynamicKey/AgoraDynamicKey/csharp/test/AgoraIO.Tests/RtmTokenTest.cs) class we are passing uid as channel name in AccessToken class constructor what is purpose of that can anyone explain this. Same code also available in [RtmTokenBuilderTest](https://github.com/AgoraIO/Tools/blob/master/DynamicKey/AgoraDynamicKey/csharp/src/AgoraIO/Rtm/RtmTokenBuilder.cs) class.
Thank you for any kind help

**Comment by sunshinexcode** [comment]
@Harsh-U-Joshi 
The design of RTM Token 006 version is like this, but version 007 doesn't have this problem. We recommend using the latest 007 version.

Refer to https://github.com/AgoraIO/Tools/blob/master/DynamicKey/AgoraDynamicKey/csharp/src/AgoraIO/TokenBuilders/RtmTokenBuilder2.cs

**Comment by Harsh-U-Joshi** [comment]
@sunshinexcode 
Okay. Thanks for reply
