### ISSUE TITLE
能不能把不同语言的sdk分开，以便使用安装

### ISSUE THREAD

**Issue by kenxudk** [AgoraIO/Tools#342]
像php这些根本不能composer安装仅自己的

**Comment by xiaojianhx** [comment]
java的，是要把源码copy下来，放到工程里？有没有中央仓库资源可以用的啊？

**Comment by sunshinexcode** [comment]
@kenxudk 
php将源码放入自己的仓库集成token.
目前各种版本语言放在一个仓库下, 方便用户查看.

**Comment by sunshinexcode** [comment]
@xiaojianhx 
java可以使用maven安装.
https://mvnrepository.com/artifact/io.agora/authentication/2.0.0

[README](https://github.com/AgoraIO/Tools/tree/master/DynamicKey/AgoraDynamicKey/java)
