### ISSUE TITLE
Problem in Building AccessToken2 || which library I have to use 

### ISSUE THREAD

**Issue by fsdsharmas771** [AgoraIO/Tools#349]
I am experiencing difficulty generating a token with user privileges to integrate chat into a live session on Agora tools. Could you please assist me with this task?"

**Comment by sunshinexcode** [comment]
@fsdsharmas771 
You can first refer to this document [integrate-token-generation](https://docs.agora.io/en/video-calling/develop/integrate-token-generation).
If you have any more questions, please feel free to provide feedback. Thank you.
