### ISSUE TITLE
Add API for synchronous token validation

### ISSUE THREAD

**Issue by ByronBecker** [AgoraIO/Tools#350]
I'm currently storing the generated RTC token in local storage, and would like to be able to verify that the generated token is valid/expired without making an API call to the server.

This way, if the token is invalid I can save a round trip (not needing to receive a 403 before refreshing the token).

Ideally this API would live in the [`agora-token` repository](https://github.com/AgoraIO/Tools/tree/master/DynamicKey/AgoraDynamicKey/nodejs) 🙏

**Comment by sunshinexcode** [comment]
@ByronBecker 
To verify whether a token is expired, you can call and use 
`
access_token = AccessToken(); 
access_token.from_string(token) 
`
to parse out the expiration time to judge. 
For reference, you can look into [parse.py](https://github.com/AgoraIO/Tools/blob/master/DynamicKey/AgoraDynamicKey/parse.py)
