### ISSUE TITLE
python3和python2 下生成的Education Token是否可用？

### ISSUE THREAD

**Issue by coffeefoam** [AgoraIO/Tools#353]
`token = EducationTokenBuilder.build_room_user_token(current_app.config['AGORAIO_APP_ID'],
                                                            current_app.config['AGORAIO_KEY'],
                                                            course_no, uid, role,
                                                            current_app.config['AGORAIO_TOKEN_EXPIRATION'])`

不知道为什么上面的代码生成了token，客户端却一直说验证失败

course_no和uid 字符串，数字全都试了一遍，还是不行

![image](https://github.com/AgoraIO/Tools/assets/1013582/4102fe71-96ff-403f-b59a-c28e25e1b6b7)
项目管理里的临时生成器却可以，参数一样，不知道为什么

**Comment by sunshinexcode** [comment]
@coffeefoam 
用代码和项目管理的临时token生成器, 逻辑是一样的. 检查一下 current_app.config['AGORAIO_TOKEN_EXPIRATION'] 这个参数值. 
你可以发一下 course_no, uid, role, current_app.config['AGORAIO_TOKEN_EXPIRATION'] 这几个参数的值, 以及在项目管理临时token生成器里选的角色.

**Comment by sunshinexcode** [comment]
@coffeefoam 
客户端验证失败, 麻烦提供一下错误信息
