### ISSUE TITLE
AgoraRTCError CAN_NOT_GET_GATEWAY_SERVER with PHP 8.2

### ISSUE THREAD

**Issue by katjai1** [AgoraIO/Tools#355]
When we're tried to use DynamicKey/AgoraDynamicKey with PHP 8.2, we started to get such error: AgoraRTCError CAN_NOT_GET_GATEWAY_SERVER: invalid vendor key, can not find appid. This code change inside Util.php fixed an issue:

```
    public static function packString($str)
    {
        return !empty($str)
            ? self::packUint16(strlen($str)) . $str
            : self::packUint16(0);
    }
```

**Comment by sunshinexcode** [comment]
@katjai1 
Can you provide a sample that reproduces the aforementioned issue after running? I need more specific information to determine the cause of the problem. Thank you.
