### ISSUE TITLE
getStats() method is no longer supported

### ISSUE THREAD

**Issue by neilyoung** [AgoraIO/Tools#359]
`Failed to execute 'getStats' on 'RTCPeerConnection': The callback-based getStats() method is no longer supported.`

On last page here:

> Have a try @ https://webdemo.agora.io/agora_webrtc_troubleshooting/

Chrome 121.0.6167.160 (arm64), MacOS

**Comment by kerash-huang** [comment]
I've encountered same error message and then I try to upgrade to version NG 4.20 ,then it can be solved.

**Comment by neilyoung** [comment]
OK, thanks for letting me know
