### ISSUE TITLE
Java 使用官方案例生成token之后，IOS无法使用

### ISSUE THREAD

**Issue by YouAnCao** [AgoraIO/Tools#36]
使用官方文档生成token（使用string 类型的 uid），在IOS端没办法建立连接；
后面通过将传递的string类型的uid干掉，传入默认值0解决问题；另外IOS端建立连接不能使用string类型的uid；该方法是不是有问题。

**Comment by plutoless** [comment]
iOS SDK如果需要使用string uid,需要使用[joinChannelByUserAccount](https://docs.agora.io/cn/Voice/API%20Reference/oc/Classes/AgoraRtcEngineKit.html#//api/name/joinChannelByUserAccount:token:channelId:joinSuccess:)方法

**Comment by plutoless** [comment]
如果用的是普通joinChannel方法，uid只能给int，这种情况下要用token builder的int uid生成方法生成token

**Comment by YouAnCao** [comment]
感谢你解答，现在着手修改到你所提到的方法。
