### ISSUE TITLE
如何renewToken

### ISSUE THREAD

**Issue by bigbean17** [AgoraIO/Tools#361]
我在使用Ruby生成token，如果没错的话应该使用的是DynamicKey2::DynamicTokenBuilder，在这个文件里面没有定义renewToken这个方法，但是在comment里面提到了renewToken，想问一下应该如何更新一个token呢？
<img width="852" alt="image" src="https://github.com/AgoraIO/Tools/assets/69971426/3aeb4fc7-e48a-4e37-966c-7a726cf3eda6">

我希望只生成一个token，所有用户只使用这一个token，我的publisher会持续不间断直播，所以不希望每天都生成一个新的token然后让用户重新加入，感谢帮助！

**Comment by sunshinexcode** [comment]
@bigbean17 
1.针对 renewToken, 含义是如果token即将过期, 重新生成token. renewToken 是 RTC SDK 方法, 需要传入新生成的 token.
<img width="1359" alt="WeChatWorkScreenshot_c7f9b6c5-5f9f-4d0c-a6b9-ab38b84b15be" src="https://github.com/AgoraIO/Tools/assets/5187981/11c5d966-5f7f-4987-9034-9ee118b32745">

2.只生成一个token，所有用户只使用这一个token
可以参考文档 https://doc.shengwang.cn/doc/rtc/android/best-practice/wildcard-token 的"生成通配 Token"部分
