### ISSUE TITLE
AGORA TOKEN GENERATION ISSUES

### ISSUE THREAD

**Issue by sixdigitguy** [AgoraIO/Tools#362]
I am having some issues connecting to token generated, I contacted agora customer care and was told my token was generated with v006 I should try v007, I installed agora with @latest, please how do I update the token generation. My agora-access-token version: 2.0.4

Here is the message:
Hi,
Upon checking, you have generated the token using the old version, which is the 006 token.
Kindly try to generate using the 007 version and see if the same issue will persist.
Regards,

**Comment by sunshinexcode** [comment]
@sixdigitguy 
Please let me know what programming language you are using, and you can integrate it using source code.
