### ISSUE TITLE
Add README.md to Provide Repository Description

### ISSUE THREAD

**Issue by sabeerbikba** [AgoraIO/Tools#367]
The repository currently lacks a description and a README.md file, which makes it difficult for visitors to understand the purpose and usage of the project. Adding a README.md file would greatly improve clarity and accessibility

**Comment by sunshinexcode** [comment]
@sabeerbikba 
Thank you for your suggestion, we will add a README description in the future.

**Comment by sunshinexcode** [comment]
@sabeerbikba 
PR https://github.com/AgoraIO/Tools/pull/374
fixed. thanks for your suggestion
