### ISSUE TITLE
Need helper for building streaming token for MediaGateway in Ruby

### ISSUE THREAD

**Issue by mlnkrish** [AgoraIO/Tools#395]
https://docs-beta.agora.io/en/media-gateway/get-started/quickstart

**Comment by sunshinexcode** [comment]
Generating a streaming key is unrelated to the token. There are two ways to generate a streaming key:

1.Method 1: You can refer to the documentation at https://docs-beta.agora.io/en/media-gateway/get-started/quickstart for a Node.js example to generate a streaming key, and then convert it into Ruby code yourself.

2.Method 2: You can generate a streaming key through an API interface. You can refer to the documentation at https://doc.shengwang.cn/doc/rtmp-gateway/restful/rtmp-gateway/operations/post-region-v1-projects-appId-rtls-ingress-streamkeys.

If you have any further questions, you can consult the relevant technical support. Thank you!
