### ISSUE TITLE
rtm的Node签名，Role取值问题

### ISSUE THREAD

**Issue by wildfire810** [AgoraIO/Tools#46]
Node签名中，
但是服务端代码
https://github.com/AgoraIO/Tools/blob/master/DynamicKey/AgoraDynamicKey/nodejs/src/RtmTokenBuilder.js
这里这么写的
const Role = {
Rtm_User: 1
}
这个部分是rtm的签名功能。
那么
https://docs.agora.io/cn/Real-time-Messaging/rtm_token?platform=All%20Platforms
这里写着“ privilege ：RTM Client 暂时只支持一种角色，将该值设为 1000”
这两个说的是一回事吗？这个取值怎么理解？
另外rtm目前也会有客户端那边需要renew token的问题嘛？这个我在两边的文档上都没看到解释。

**Comment by plutoless** [comment]
你看下代码可以看到这个role会添加这个privilege，所以说的是一件事
renewToken的方法可以参考
https://docs.agora.io/cn/Real-time-Messaging/API%20Reference/RTM_oc/Protocols/AgoraRtmDelegate.html#//api/name/rtmKitTokenDidExpire:
