### ISSUE TITLE
大神在么，能帮忙看下 go生成token的问题么 

### ISSUE THREAD

**Issue by dio17337548611** [AgoraIO/Tools#48]
我这边用go生成token，不知道为何，token中总是有空格。
然后传递给flutter端，然后加入频道失败。
下边是我的go代码
![image](https://user-images.githubusercontent.com/58875519/71504229-91e23700-28b3-11ea-9c85-c9869495ffdb.png)

这是 用这些代码生成的token:
00679ac8152c1394babaf20f341ad76e04cIACcj7qfrVmNJJW/lDpwiq8z0wMp45CSt UlUpLBOT7M8uuR0YQAAAAAIgAzFjECH/QGXgQAAQAAAAAAAgAAAAAAAwAAAAAABAAAAAAA
这是 flutter收到的token打印的log：
![image](https://user-images.githubusercontent.com/58875519/71504710-71b37780-28b5-11ea-9ebc-f2613ed1586a.png)
感觉go后端生成的token其中不知道为何增加了个换行，
手机端flutter这边获得到的就是个带有空格的token。
就加入频道一直失败了

**Comment by plutoless** [comment]
token是没有空格或者换行的，试试去掉换行或者空格看看

**Comment by dio17337548611** [comment]
> token是没有空格或者换行的，试试去掉换行或者空格看看
我这边后台坚持说这是他们生成的原始token，这个是他们的代码 箭头中的常量 值是1
![image](https://user-images.githubusercontent.com/58875519/71565810-39967980-2aed-11ea-8d2e-bd8b438adc39.png)
下边是他们生成的原始token：
![image](https://user-images.githubusercontent.com/58875519/71565877-d22cf980-2aed-11ea-91e7-1324e067ccb6.png)
第一token 可以正常使用
第二个token就不行了 感觉像是有了个回车 换行一样。
大神 我们这个要怎么拯救啊。。。

**Comment by plutoless** [comment]
![image](https://user-images.githubusercontent.com/471561/71566063-4b791c00-2aef-11ea-9c3d-a23d2f4b2ce5.png)
我用 https://github.com/AgoraIO/Tools/tree/master/DynamicKey/AgoraDynamicKey/go/sample/RtcTokenBuilder 的示例代码跑，并没有空格

**Comment by dio17337548611** [comment]
> ![image](https://user-images.githubusercontent.com/471561/71566063-4b791c00-2aef-11ea-9c3d-a23d2f4b2ce5.png)
> 我用 https://github.com/AgoraIO/Tools/tree/master/DynamicKey/AgoraDynamicKey/go/sample/RtcTokenBuilder 的示例代码跑，并没有空格

好的 我让他们试下

**Comment by dio17337548611** [comment]
> ![image](https://user-images.githubusercontent.com/471561/71566063-4b791c00-2aef-11ea-9c3d-a23d2f4b2ce5.png)
> 我用 https://github.com/AgoraIO/Tools/tree/master/DynamicKey/AgoraDynamicKey/go/sample/RtcTokenBuilder 的示例代码跑，并没有空格

大神 这个uid可以是5位的随机数么
![image](https://user-images.githubusercontent.com/58875519/71581424-1ba63480-2b40-11ea-8413-7839798f60f4.png)
他这个方法:
          AgoraRtcEngine.joinChannel(token, bean.channel.trim(), null, 2882341273);

**Comment by plutoless** [comment]
uid可以是uint32范围内的任意数，但算token的时候要确保token的channel和uid和实际加入的一致
