### ISSUE TITLE
接入accesstoken后，运行时报undefined symbol: crc32

### ISSUE THREAD

**Issue by pudy** [AgoraIO/Tools#5]
make成功生成了.so文件
引入lua时报错undefined symbol: crc32
亲问下crc32实现的c++库是啥，需要额外引用是吗

**Comment by viewcode** [comment]
需要zlib库，请确认下是否添加了zlib的链接库。
参考sample
g++ -ggdb  -std=c++0x -O0 -I../../  AccessToken_test.cpp  main.cpp -lz -lcrypto -std=c++0x -lgtest -lpthread -o TestDynamicKey.exe

**Comment by pudy** [comment]
> 需要zlib库，请确认下是否添加了zlib的链接库。
> 参考sample
> g++ -ggdb -std=c++0x -O0 -I../../ AccessToken_test.cpp main.cpp -lz -lcrypto -std=c++0x -lgtest -lpthread -o TestDynamicKey.exe

谢谢，修改Makefile后好使了。
