### ISSUE TITLE
io.agora.rtm.RtmTokenBuilder 

### ISSUE THREAD

**Issue by tj3333** [AgoraIO/Tools#51]
io.agora.rtm.RtmTokenBuilder not found in android java

**Comment by plutoless** [comment]
it's a server java project. please use eclipse to open it

**Comment by swadeshAndroid** [comment]
io.agora.rtm.RtmTokenBuilder 
where we want to get this lib file to add in my project.
(reply on  s.deshmukh@ehealthsystem.in)

**Comment by sadiea** [comment]
you can find io.agora.rtm.RtmTokenBuilder in this file(https://github.com/AgoraIO/Tools/blob/master/DynamicKey/AgoraDynamicKey/java/src/main/java/io/agora/rtm/RtmTokenBuilder.java).

to add that in your project, you should copy 'media' and 'rtm' folder to your project in this catalog(https://github.com/AgoraIO/Tools/tree/master/DynamicKey/AgoraDynamicKey/java/src/main/java/io/agora).
