### ISSUE TITLE
Follow go modules rule, import path should be domain format

### ISSUE THREAD

**Issue by chihkaiyu** [AgoraIO/Tools#58]
Hi,
We're using Agora's Go SDK and we're now migrating our code from vendor to go modules since golang 1.14 had been released and go modules now is official on production.  

Note that, from golang 1.13, requires that all import path should start with a domain.  
For example, RtcTokenBuilder import `accesstoken` should be:  
```
github.com/AgoraIO/DynamicKey/AgoraDynamicKey/go/src/AccessToken
```
not simple `accesstoken`, even it's an internal package.
https://github.com/AgoraIO/Tools/blob/master/DynamicKey/AgoraDynamicKey/go/src/RtcTokenBuilder/RtcTokenBuilder.go#L4

Would you please revise Golang's SDK for following the rules?  Thank you very much!

Reference: https://blog.csdn.net/qq_23109825/article/details/103604685

**Comment by plutoless** [comment]
thanks for notifying, i will arrange updates shortly.

**Comment by bastengao** [comment]
https://github.com/AgoraIO/Tools/pull/65 I submit a PR.

**Comment by bastengao** [comment]
I add a go module part https://github.com/bastengao/AgoraDynamicKey
