### ISSUE TITLE
 Can you provide C# support?

### ISSUE THREAD

**Issue by hellojuly** [AgoraIO/Tools#6]
Can you provide C# support?

we need it

**Comment by plutoless** [comment]
We are working on it, will try to finish this by end of March

**Comment by dukecheng** [comment]
@hellojuly I have done the C# AccessToken part, if you need please call me, later I will prepare a PR to this rep.

**Comment by plutoless** [comment]
sorry we didn't have time to really work on this due to tight project schedule. @DukeCheng it would be great to make a PR and i will help review and merge it for you.

**Comment by fullstack10** [comment]
I am also looking for c# code. i generated the token successfully by using c# code which is provided here but not able to join the call can you please help me for this 
I am getting the below error please follow:
![Uploading image.png…]()

**Comment by sunshinexcode** [comment]
C# has already been provided, refer to https://github.com/AgoraIO/Tools/tree/master/DynamicKey/AgoraDynamicKey/csharp
