### ISSUE TITLE
php生成rtctoken

### ISSUE THREAD

**Issue by haydenliu66** [AgoraIO/Tools#66]
public static function buildTokenWithUid($appID, $appCertificate, $channelName, $uid, $role, $privilegeExpireTs){
        return RtcTokenBuilder::buildTokenWithUserAccount($appID, $appCertificate, $channelName, $uid, $role, $privilegeExpireTs);
    }

这个RtcTokenBuilder类的方法buildTokenWithUid同样还是调用buildTokenWithUserAccount，那这区别在哪里？为啥用两个方法？

**Comment by plutoless** [comment]
https://docs.agora.io/cn/Audio%20Broadcast/token_server_nodejs?platform=Node.js#api-参考
一个是为int uid生成的，还有一个是为了string uid

**Comment by haydenliu66** [comment]
您好。请看我上面所说的，你们两个方法其实是同一个吖。为int uid生成token的方法就是直接调用为string uid的方法.非常困惑吖。这个int uid方法就是直接调用string uid方法。没有任何处理。
public static function buildTokenWithUid($appID, $appCertificate, $channelName, $uid, $role, $privilegeExpireTs){
    return RtcTokenBuilder::buildTokenWithUserAccount($appID, $appCertificate, $channelName, $uid, $role, $privilegeExpireTs);
}

**Comment by plutoless** [comment]
@haydenliu66 您好，加解密逻辑上确实如此，这样区分只是为了能让使用者更加清晰地明确自己应该用哪个方法，如果是int uid用buildTokenWithUid就好，反之则用buildTokenWithUserAccount。这个逻辑是正确的，您只要根据您的实际情况使用对应的api就行，不需要关心他们的内部实现的

**Comment by jalomari** [comment]
hello ... I'm using sample php "RtcTokenBuilderSample" and "RtmTokenBuilderSample" to generate the token, but always showing me error in console "invalid iv length" 
any solution please?
