### ISSUE TITLE
Invalid Token 

### ISSUE THREAD

**Issue by georgemichailou** [AgoraIO/Tools#67]
I try this class to create a token :

https://github.com/AgoraIO/Tools/blob/master/DynamicKey/AgoraDynamicKey/csharp/src/AgoraIO/Media/DynamicKey4.cs

        public static string GenerateMediaChannelKey() //throws Exception
        {
            String appID = "xxxxxxxx";
            String appCertificate = "xxxxxxxx";
            String channel = "1234";

            int ts = GetTime(); // The timestamp, represented by the number of seconds elapsed since 1 / 1 / 1970
            int r = new Random().Next();
            string uid = 0.ToString();
            int expiredTs = 0; //Call Expiration Timestamp , 0 for no limit

            return DynamicKey4.generateMediaChannelKey(appID, appCertificate, channel, ts, r, uid, expiredTs);
        }

        public static int GetTime()
        {
            var ts = DateTime.UtcNow - new DateTime(1970, 1, 1);
            return (int)ts.TotalSeconds;
        }

I get this error on console 

Agora-SDK [ERROR]: [B643A] Get server node failed [NO_AUTHORIZED] https://webrtc2-ap-web-1.agora.io/api/v1 NO_AUTHORIZED

When i create a temp token from console.agora.io is working without error.

**Comment by plutoless** [comment]
@georgemichailou could you pls try using the access token version? as dynamic key4 is a bit out dated.

**Comment by georgemichailou** [comment]
Thanks @plutoless , the access token is working perfect !!

Can i ask you something ?

I cant understand the values for _ts  and _expiredTs.

> [1]: The timestamp, represented by the number of seconds elapsed since 1/1/1970. The user can use the Dynamic Key to access the Agora service within 5 minutes after the Dynamic Key is generated. If the user does not access the Agora service after 5 minutes, the Dynamic Key is no longer valid.
> 
> [2]: Set the value to 0 for no time limit. Indicates the exact time when a user can no longer use the Agora service (for example, when a user is forced to leave an ongoing call). When the value is set for Call Expiration Timestamp, it does not mean that the Dynamic Key will be expired, but means that the user will be kicked out of the channel.

For the _ts the default value is 

```
uint _ts = (uint)(Utils.Utils.getTimestamp() + 24 * 3600);
```
What is the 24 * 3600 ?

For the _expiredTs if i want to set 30 minutes expiration what can i do ? The 0 value is for no time limit.

This one is not a good practise ?

```
uint _ts = (uint)(Utils.Utils.getTimestamp()); // the number of seconds elapsed since 1/1/1970
uint _expiredTs = (uint)(Utils.Utils.getTimestamp() + 30*60); //30 minutes expiration
```

Thanks.

**Comment by plutoless** [comment]
i think you can leave 24 * 3600 as it is. A token will be invalid after 24 hours by default. In most cases you don't need to care about this parameter.
if you want to set 30 minutes for expiredTs, set it to currentTimeStamp + 30 * 60

**Comment by georgemichailou** [comment]
One more question @plutoless . If I want to create an one to one communication. Can i use the same token on both sides or i will create the new one on every user ? (with same channel id)

**Comment by plutoless** [comment]
if you specify uid when you calculate a token. the token can only be used by corresponding user.
if you want to provide a token which works for any user joining this channel, provide uid 0 when calculating a token - although this is causing some security concerns.

**Comment by jb-7-jay** [comment]
if you are manually testing this scenario then you must add the same uid at the client-side while joining the room which is there while generating the token.
