### ISSUE TITLE
Generate token on server, not able to connect to channel on client. 

### ISSUE THREAD

**Issue by uh-vish** [AgoraIO/Tools#69]
I am trying to create AccessToken with appID, appCertificate, uid, channelName, expiry.

Token is build, but clients are not able to connect channel.

**Comment by uh-vish** [comment]
Tried both AccessToken and RTCTokenBuilder. Nothing working. Please help here.

**Comment by plutoless** [comment]
could you pls provide a sample token you generated and corresponding channel/uid?

**Comment by Valentinishe** [comment]
same problem...
@plutoless 
token: "006c3253402079d43e1bec8bede5ac67353IACKdx8S13bnQ/z0p/4fmqIi+ZigmMrc9i5hmlvix+oTYNNmJ22ZRoC5IgBzv7SV/3+xXgQAAQCPPLBeAgCPPLBeAwCPPLBeBACPPLBe"
channel: 
"5e821a09c4dd290004edcbf6"

account: "5e81da1294fd26091756e145"

**Comment by uh-vish** [comment]
**Channel Name**
rtqIFE2Nci

**uid**
123

**Token**
0061a74f852a20341f395c9c14e42fa0157IAAnR/PxoVZoQnz1qvaVeGw6y7O4c4aID2+XM0OojRouLZ5Bmh7SY0iIIgDV57NsHoOxXgQAAQCuP7BeAgCuP7BeAwCuP7BeBACuP7Be

**Comment by uh-vish** [comment]
@plutoless

**Comment by plutoless** [comment]
@uh-vish @Valentinishe looks like both of your token are correct. could you pls show me your code snippet for joining channel? btw in our dashboard there's a mechanism where you can generate temp token, does that work for you?

**Comment by Valentinishe** [comment]
@plutoless 
the temporary token works correctly, but the generated token does not (

I did everything on the guide - from official site https://github.com/AgoraIO/Tools/tree/master/DynamicKey/AgoraDynamicKey/nodejs

But I don’t understand why this is happening.
If I generate a temporary token on your site, then everything works fine.
If I generate a token without specifying a specific user id (userId = 0), then everything is fine.

But if I specify a specific user id when generating a token (ex.  account = "5e821a09c2ff111114abaab2"), communication is not established and there are no errors.

const { RtcTokenBuilder, RtcRole } = require('agora-access-token');   //    version "^2.0.4"
const moment = require('moment');
```
class AgoraService {

  
  static generateTokenRTC({ channelId, userId }) {
  
    const appID = process.env.AGORA_APP_ID;
    const appCertificate = process.env.AGORA_APP_CERTIFICATE;
    const channelName = channelId;
    // const account = userId;  // 5eab3d57e7d28a00049fbc48
    const account = 0;
    const role = RtcRole.PUBLISHER;
    const expirationTimeInSeconds = 3600;
    const currentTimestamp = Math.floor(Date.now() / 1000)
    const privilegeExpiredTs = currentTimestamp + expirationTimeInSeconds;

    return RtcTokenBuilder.buildTokenWithAccount(
       appID, 
       appCertificate, 
       channelName, 
       account, // 5eab3d57e7d28a00049fbc48
       role,
       privilegeExpiredTs
    );

    }
}


module.exports = AgoraService;
```

**Comment by plutoless** [comment]
@Valentinishe in this case it's usually because the uid you are using to join the channel does not match the one you used to generate the token. could you pls show me your code snippet for how joinning the channel?
the temp token generated in dashboard also does not check uid

**Comment by uh-vish** [comment]
@plutoless Will try with generating token for every uid.

**Comment by vishnudassoman** [comment]
Hi @plutoless ,
I am using the C# library for token generation. I am also facing the same issue.  I am not passing any user id for the token generation as well as while joining the call.  The code I use for the token generation is given below.
    private string _appId = "cdc6d4efe5ab4fa6ba5c109e6423fa19";
        private string _appCertificate = <I have removed it>;
        private string _channelName = "Demo";
        private string _uid = "";
        private uint _ts = (uint)((DateTimeOffset)DateTime.UtcNow).ToUnixTimeSeconds();
        private uint _salt = 1;
        private uint _expiredTs = 0;
   AccessToken token = new AccessToken(_appId, _appCertificate, _channelName, _uid, _ts, _salt);
            token.message.ts = _ts;
            token.message.salt = _salt;
            token.addPrivilege(Privileges.kJoinChannel, _expiredTs);

When I use this token to join the call, it is sowing me this message - "Client join failed DYNAMIC_KEY_TIMEOUT. The time to join the channel is greater than 5 seconds ."

When I use the token generated through the Agora console, is working fine. 
Could you please help me to find out the root cause for this issue?

Thanks
Vishnu

**Comment by vishnudassoman** [comment]
Here is the token generated.
006cdc6d4efe5ab4fa6ba5c109e6423fa19IACS93Sb6kT7A6wrcWP4i/tj9NlzfIFq8XjxS4x/M/fg4Z5wcHYAAAAAEAABAAAADXSNXwEAAQAAAAAA

**Comment by SezerFidanci** [comment]
hi @vishnudassoman , As @uh-vish  says, uid needs to be specified on client side. 
For example android : 

Default sample project code;
 rtcEngine().joinChannel(token, config().getChannelName(), "", 0);

here it is necessary to write uid instead of 0 in joinChannel method.

 rtcEngine().joinChannel(token, config().getChannelName(), "", 1234);

**Comment by vol-and** [comment]
@plutoless , can you make it clear why I get Error:  DYNAMIC_USE_STATIC_KEY using php ?
I've noticed, that console and rtcTokenBuilder producing different Tokens (lenght). If I use Token from Console, everything is fine. But if I use Token from rtcTokenBuilder - I get this error.

Console Token: 0068bedd2631cf24edea47479b64ad219ceIAAYXDdhxjKQyDWQEoqK0qEiAYo+dLSyd/YNAaflVD4PJO/ZQc0AAAAAEACMMKzfQDg1YAEAAQA/ODVg

rtcTokenBuilder:  0068bedd2631cf24edea47479b64ad219ceIAADpmWghbJIToZQMC9YrQjBhtFgpdZS4tIlOkXTjk+LKe/ZQc0h39v0IgCa0wUAjQY2YAQAAQA5tjRgAwA5tjRgAgA5tjRgBAA5tjRg

Pls help!!

**Comment by plutoless** [comment]
@plutoless DYNAMIC_USE_STATIC_KEY means you have turned on token feature on dashboard.agora.io, while you are not using token to join a channel. could you pls show me your api call for joinChannel?

**Comment by martianmartian** [comment]
https://github.com/AgoraIO/Tools/issues/231
here, i showed my code in swift, basically same issue here. please help.... 
my case has different condition tho: when the server starts, it works totally fine for a while, during which all token can be used without issues. 
but after a few hours, the tokens are still generated fine, but the ios(swift) is not able to join the channel anymore, without any error message. the returned value from joinChannel is 0, which seems fine, but joinSuccess callback has not been fired, and audio has not been turned on. 

please help...

**Comment by future-mine** [comment]
Did anyone get a solution?
I also got an issue with the generated token.
It doesn't show another user which is connected to the room on another side.
It works fine for temp token.

**Comment by akanz** [comment]
I am having the same issue here. the temp token generated works fine, but the one generated on the server shows blank screen.

**Comment by sunshinexcode** [comment]
could you pls provide a sample token you generated and corresponding appId/channel/uid. 
describe which language and method is used to generate token

RTC Token Demo: https://webdemo.agora.io/agora-web-showcase/examples/Agora-Web-Tutorial-1to1-Web which can verify.

**Comment by gwhizoftv** [comment]
DOn't know if it will help but this is working well for us: https://github.com/gwhizoftv/Agora-Node-TokenServer/blob/master/index.js

**Comment by akanz** [comment]
I'm using Agora as the 3rd party call service for getstream. will test @sunshinexcode @gwhizoftv

**Comment by sunshinexcode** [comment]
this issue closed. If hitting some problem, create new issue

**Comment by yasintz** [comment]
I was experiencing the same issue and noticed I wrongly stored the app certificate.

**Comment by Immortalpk** [comment]
> @Valentinishe in this case it's usually because the uid you are using to join the channel does not match the one you used to generate the token. could you pls show me your code snippet for how joinning the channel? the temp token generated in dashboard also does not check uid

Thanks a-lot bro you saved my job.
