### ISSUE TITLE
Suggestion: Tag your releases

### ISSUE THREAD

**Issue by prene** [AgoraIO/Tools#71]
Would be great if you could tag your releases. This way I, as a user, can easily see changes introduced and decide whether I like to deploy that new version or not.

**Comment by plutoless** [comment]
thanks for the suggestion. i will tag following releases

**Comment by Invertisment** [comment]
What about not only tagging the releases but also deploying them to artifact repositories? For instance for Java it would be search.maven.org.

**Comment by plutoless** [comment]
@Invertisment thanks we are checking the feasibility. will update once done.
