### ISSUE TITLE
'str' object has no attribute 'decode' in generateMediaChannelKey Python3

### ISSUE THREAD

**Issue by Sugamm** [AgoraIO/Tools#72]
Hey team, 

I'm making a share screen functionality, as per the documentation https://docs.agora.io/en/Interactive%20Broadcast/screensharing_web?platform=Web

To do that we required channelKey in this function
screenClient.join(channelKey, channel, null, function(uid) {... 

Then I followed how to obtain a channel key (https://docs.agora.io/en/Agora%20Platform/channel_key?platform=All%20Platforms)

I'm using Python3 and created a file dynamickey5.py
if I pass uid=123 in generateMediaChannelKey function
`screenshare_key = generateMediaChannelKey(appID, appCertificate, channel_name, unixts, randomint, uid, 0)`
then this error occur
`an integer is required (got type str)`

and if I pass uid as int(uid)
`screenshare_key = generateMediaChannelKey(appID, appCertificate, channel_name, unixts, randomint, int(uid), 0)`
then this error occurs
`'str' object has no attribute 'decode'`

Help!

**Comment by plutoless** [comment]
@Sugamm  thanks for the issue. the channel media key is out dated, could you pls refer to latest access token to authenticate joining users?
you may find the docs for python here https://docs.agora.io/en/cloud-recording/token_server_python?platform=Python

**Comment by Sugamm** [comment]
@plutoless thanks for the reply, I followed the same to connect video call and it is working amazing, but when I'm trying to do screen share in that function following this document (https://docs.agora.io/en/Interactive%20Broadcast/screensharing_web?platform=Web)
````
var screenClient = AgoraRTC.createClient({mode: 'rtc', codec: 'vp8'});
screenClient.init(key, function() {
 screenClient.join(channelKey, channel, null, function(uid) {
  screenClient.publish(screenStream);
 }
  }
````

What should I pass in **channelKey** ?

**Comment by plutoless** [comment]
it's the same concept as you used to stream the camera video. Here screen share is like a second virtual user which streams screen capture video only. so you will need to provide a uid at screenClient.join function (3rd param) and calculate a token for screen share client (with corresponding channel and screen client uid). then you should be able to make screen client join the channel properly

**Comment by Sugamm** [comment]
Thanks @plutoless it worked. Request you to please update your documentation.
