### ISSUE TITLE
Ruby gem

### ISSUE THREAD

**Issue by rahlusmorsi** [AgoraIO/Tools#73]
I see you've setup a Ruby gemspec for agora_dynamic_key and have referenced rubygems.  Do you have plans in the near future to publish this gem there?  If it should  already be there, I am unable to locate it.

<img width="442" alt="Screen Shot 2020-05-05 at 5 11 15 PM" src="https://user-images.githubusercontent.com/6517972/81121030-789d6700-8ef3-11ea-9c28-ac40fd802fc1.png">

**Comment by abelorian** [comment]
I published the gem using this source code https://rubygems.org/gems/agora_dynamic_key

Usage example: https://gist.github.com/abelorian/200696537b8b4e1bee5ac2caeb7f624a

**Comment by Invertisment** [comment]
They don't have maven packages for Java too. It's quite hard to manage them by hand and copy them. I also need to copy and load one Agora library using `LD_LIBRARY_PATH` and this is also cumbersome to manage. So this one will make it two as I'll need to build this one as well. :(

I want to standartize my process and forget about low level details but there wasn't enough effort to do it easy for devs to use these libraries.

**Comment by sunshinexcode** [comment]
@Invertisment 
SDK can be obtained automatically via [Maven's dependency management](https://mvnrepository.com/artifact/io.agora/authentication) by adding the following configuration in the application's Project Object Model (POM) file:

```
<dependency>
    <groupId>io.agora</groupId>
    <artifactId>authentication</artifactId>
    <version>2.0.0</version>
</dependency>
```
