### ISSUE TITLE
go: rtmtokenbuilder.BuildToken wrong args

### ISSUE THREAD

**Issue by bastengao** [AgoraIO/Tools#79]
https://github.com/AgoraIO/Tools/blob/fbe41e5e1c12e91262ab177559b41e8300b27b08/DynamicKey/AgoraDynamicKey/go/src/RtmTokenBuilder/RtmTokenBuilder.go#L31

`userAccount` should be passed to `accesstoken.CreateAccessToken2(appID, appCertificate, channelName, userAccount)` as uid

**Comment by plutoless** [comment]
@bastengao thanks for raising the issue. it's in fact by design that rtm token is using channelName field as its userAccount field. i agree it's not perfect but this is indeed current design.
I'll close this in this case, feel free to reopen if you have different opinions.
