### ISSUE TITLE
Getting: Get server node failed [NO_AUTHORIZED] when tried to use a token created from Server [Golang]

### ISSUE THREAD

**Issue by nitiprabhu** [AgoraIO/Tools#88]
Hi Team, 

I tried creating the token with UUID using the Golang library as below: 

package main

```
import (
	"fmt"
	rtctokenbuilder "github.com/AgoraIO/Tools/DynamicKey/AgoraDynamicKey/go/src/RtcTokenBuilder"
	"github.com/google/uuid"
)

func main() {

	appId := "<app-id>"
	appCertificate := "<app-secret>"

	result, err := rtctokenbuilder.BuildTokenWithUID(appId, appCertificate, "one1", uuid.New().ID(), rtctokenbuilder.RoleAttendee, 0)
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Printf("Token with userAccount: %s\n", result)
	}
}
```
I got the token successfully too, but when I tried to verify it using the UI available: https://webdemo.agora.io/agora-web-showcase/examples/Agora-Web-Tutorial-1to1-Web, I am getting NOT_AUTHORIZED error as below:

`00:20:26:928 Agora-SDK [ERROR]: [8AB3F] Get server node failed [NO_AUTHORIZED] https://webrtc2-ap-web-1.agora.io/api/v1 NO_AUTHORIZED` (attached the screenshot for the reference as well)

![Screenshot 2020-07-04 at 12 25 36 AM](https://user-images.githubusercontent.com/15167151/86492874-0a5b1080-bd8d-11ea-9d6c-14bd38868a8b.png)

For reference, I took the appId and appCertificate from here, attached in the screenshot:
![Screenshot 2020-07-04 at 12 22 53 AM](https://user-images.githubusercontent.com/15167151/86492742-bcdea380-bd8c-11ea-937c-1d5867244480.png)

Could anybody help me, what is going wrong here? What is the solution to fix this issue?

**Comment by plutoless** [comment]
looks like the token you used here is "<>", is this a proper token generated by your server? the error means you are not providing a valid token

**Comment by nitiprabhu** [comment]
@plutoless Yes, those are valid token generated from the server only, I have just masked it as <> for security purpose. 

The output of **result** (as in the go code attached) is given as a token. (<>).

**Comment by plutoless** [comment]
ok. in this case, could you pls double check if the channel name and uid you used to generate the token matches with the one you used to join a channel?

**Comment by plutoless** [comment]
you may generate a test token for me to check, it can expire in 1 min so that it will not cause you any issues.

**Comment by nitiprabhu** [comment]
> ok. in this case, could you pls double check if the channel name and uid you used to generate the token matches with the one you used to join a channel?

Got it, in this UI, need to pass UID which are available in the **ADVANCED SETTINGS**. It worked, thanks for the help.

**Comment by niraj-lal-rahi** [comment]
$appID = APP_ID
$appCertificate =CERTIFICATE_KEY;
$channelName = "test";
$uid = uniqid();
$uidStr = "$uid";
$role = RtcTokenBuilder::RolePublisher;
$expireTimeInSeconds = 3600;
$currentTimestamp = (new DateTime("now", new DateTimeZone('GMT+5:30')))->getTimestamp();
$privilegeExpiredTs = $currentTimestamp + $expireTimeInSeconds;
$token = RtcTokenBuilder::buildTokenWithUid($appID, $appCertificate, $channelName, $uid, $role, $privilegeExpiredTs);


I don't know what is wrong in token generated dynamic, does not allow to broadcast : Join failed: NO_AUTHORIZED.

If I only change $token variable to static temp token then it worked.

Console mode is testing : 
Certificate is enabled.

**Comment by hkmsadek** [comment]
I am getting same error while generating a token using node server :(
