### ISSUE TITLE
求C#版本的Token生成方法

### ISSUE THREAD

**Issue by sipo1209** [AgoraIO/Tools#9]
求C#版本的Token生成方法

**Comment by plutoless** [comment]
抱歉 已经在我们的计划里了，但由于优先级的问题暂时还没有排上，这边如果有可能也可以参照现有的C++写一下

**Comment by sipo1209** [comment]
太复杂了…… 自己写不出来…… 哎。这个多久能搞定呢？

**Comment by plutoless** [comment]
Q3也许可以加上

**Comment by dukecheng** [comment]
@sipo1209 你需要的是哪部分? AccessToken. DynamicKey3, SignallingToken 的部分我已经写出来了,

**Comment by sunshinexcode** [comment]
C# has already been provided, refer to https://github.com/AgoraIO/Tools/tree/master/DynamicKey/AgoraDynamicKey/csharp
