### ISSUE TITLE
Add more detailed guides in ReadMe for Csharp.

### ISSUE THREAD

**Issue by emmazhong-agora** [AgoraIO/Tools#95]
Could you please add the following lines to Csharp sample code ReadMe? Customer firstly hits the issues easily. 
1- There are 2 different classes, one to generate key and another one to generate token (generated token start with 006)
2- UID string parameter preferred to be sent as empty string.
3- TS (time stamp) should be for next day or at least after 2 or 3 hours from now time stamp.

**Comment by Hoang-Minh** [comment]
Hi @EmmaAzureAgora are you able to generate rtc token that is useable ? I'm currently having an issue to generate a valid token. I have exactly the same code in `https://github.com/AgoraIO/Tools/tree/master/DynamicKey/AgoraDynamicKey` but the key is not valid at all. Wonder if you have run into the same issue and how did you fix it ? Thank you
